/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Axe_small_Golden_1: Mesh;
    Axe_small_Golden_2: Mesh;
    Axe_small_Golden_3: Mesh;
    Axe_small_Golden_4: Mesh;
  };
  materials: {
    DarkWood: MeshStandardMaterial;
    LightWood: MeshStandardMaterial;
    Golden: MeshStandardMaterial;
    LightGold: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/Axe_small_Golden.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Axe_small_Golden_1.geometry}
          material={materials.DarkWood}
        />
        <mesh
          geometry={nodes.Axe_small_Golden_2.geometry}
          material={materials.LightWood}
        />
        <mesh
          geometry={nodes.Axe_small_Golden_3.geometry}
          material={materials.Golden}
        />
        <mesh
          geometry={nodes.Axe_small_Golden_4.geometry}
          material={materials.LightGold}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/Axe_small_Golden.glb");
