/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Backpack_1: Mesh;
    Backpack_2: Mesh;
    Backpack_3: Mesh;
  };
  materials: {
    DarkBrown: MeshStandardMaterial;
    Brown: MeshStandardMaterial;
    Gold: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/Backpack.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Backpack_1.geometry}
          material={materials.DarkBrown}
        />
        <mesh geometry={nodes.Backpack_2.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Backpack_3.geometry} material={materials.Gold} />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/Backpack.glb");
