/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Bag_1: Mesh;
    Bag_2: Mesh;
    Bag_3: Mesh;
  };
  materials: {
    Brown: MeshStandardMaterial;
    DarkBrown: MeshStandardMaterial;
    Gold: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/Bag.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={71.17}>
        <mesh geometry={nodes.Bag_1.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Bag_2.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Bag_3.geometry} material={materials.Gold} />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/Bag.glb");
