/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Book2_Closed_1: Mesh;
    Book2_Closed_2: Mesh;
    Book2_Closed_3: Mesh;
  };
  materials: {
    DarkRed: MeshStandardMaterial;
    Golden: MeshStandardMaterial;
    Beige: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/Book2_Closed.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Book2_Closed_1.geometry}
          material={materials.DarkRed}
        />
        <mesh
          geometry={nodes.Book2_Closed_2.geometry}
          material={materials.Golden}
        />
        <mesh
          geometry={nodes.Book2_Closed_3.geometry}
          material={materials.Beige}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/Book2_Closed.glb");
