/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Book4_Open_1: Mesh;
    Book4_Open_2: Mesh;
    Book4_Open_3: Mesh;
  };
  materials: {
    Teal: MeshStandardMaterial;
    Beige: MeshStandardMaterial;
    DarkRed: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/Book4_Open.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Book4_Open_1.geometry}
          material={materials.Teal}
        />
        <mesh
          geometry={nodes.Book4_Open_2.geometry}
          material={materials.Beige}
        />
        <mesh
          geometry={nodes.Book4_Open_3.geometry}
          material={materials.DarkRed}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/Book4_Open.glb");
