/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Bow_Wooden_1: Mesh;
    Bow_Wooden_2: Mesh;
    Bow_Wooden_3: Mesh;
  };
  materials: {
    DarkWood: MeshStandardMaterial;
    LightWood: MeshStandardMaterial;
    White: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/Bow_Wooden.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Bow_Wooden_1.geometry}
          material={materials.DarkWood}
        />
        <mesh
          geometry={nodes.Bow_Wooden_2.geometry}
          material={materials.LightWood}
        />
        <mesh
          geometry={nodes.Bow_Wooden_3.geometry}
          material={materials.White}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/Bow_Wooden.glb");
