/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Chest_Ingots_1: Mesh;
    Chest_Ingots_2: Mesh;
    Chest_Ingots_3: Mesh;
    Chest_Ingots_4: Mesh;
  };
  materials: {
    Gold: MeshStandardMaterial;
    DarkMetal: MeshStandardMaterial;
    Wood: MeshStandardMaterial;
    Metal: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/Chest_Ingots.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Chest_Ingots_1.geometry}
          material={materials.Gold}
        />
        <mesh
          geometry={nodes.Chest_Ingots_2.geometry}
          material={materials.DarkMetal}
        />
        <mesh
          geometry={nodes.Chest_Ingots_3.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Chest_Ingots_4.geometry}
          material={materials.Metal}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/Chest_Ingots.glb");
