/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    ChickenLeg_1: Mesh;
    ChickenLeg_2: Mesh;
  };
  materials: {
    Beige: MeshStandardMaterial;
    Brown: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/ChickenLeg.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.ChickenLeg_1.geometry}
          material={materials.Beige}
        />
        <mesh
          geometry={nodes.ChickenLeg_2.geometry}
          material={materials.Brown}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/ChickenLeg.glb");
