/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Dagger_1: Mesh;
    Dagger_2: Mesh;
    Dagger_3: Mesh;
    Dagger_4: Mesh;
    Dagger_5: Mesh;
  };
  materials: {
    DarkSteel: MeshStandardMaterial;
    DarkWood: MeshStandardMaterial;
    LightWood: MeshStandardMaterial;
    LightSteel: MeshStandardMaterial;
    Steel: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/Dagger.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Dagger_1.geometry}
          material={materials.DarkSteel}
        />
        <mesh
          geometry={nodes.Dagger_2.geometry}
          material={materials.DarkWood}
        />
        <mesh
          geometry={nodes.Dagger_3.geometry}
          material={materials.LightWood}
        />
        <mesh
          geometry={nodes.Dagger_4.geometry}
          material={materials.LightSteel}
        />
        <mesh geometry={nodes.Dagger_5.geometry} material={materials.Steel} />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/Dagger.glb");
