/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Dart_1: Mesh;
    Dart_2: Mesh;
    Dart_3: Mesh;
    Dart_4: Mesh;
  };
  materials: {
    DarkRed: MeshStandardMaterial;
    LightWood: MeshStandardMaterial;
    Steel: MeshStandardMaterial;
    LightSteel: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/Dart.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Dart_1.geometry} material={materials.DarkRed} />
        <mesh geometry={nodes.Dart_2.geometry} material={materials.LightWood} />
        <mesh geometry={nodes.Dart_3.geometry} material={materials.Steel} />
        <mesh
          geometry={nodes.Dart_4.geometry}
          material={materials.LightSteel}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/Dart.glb");
