/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Mineral_1: Mesh;
    Mineral_2: Mesh;
  };
  materials: {
    Grey: MeshStandardMaterial;
    Pink: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/Mineral.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          name="Mineral_1"
          geometry={nodes.Mineral_1.geometry}
          material={materials.Grey}
          morphTargetDictionary={nodes.Mineral_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Mineral_1.morphTargetInfluences}
        />
        <mesh
          name="Mineral_2"
          geometry={nodes.Mineral_2.geometry}
          material={materials.Pink}
          morphTargetDictionary={nodes.Mineral_2.morphTargetDictionary}
          morphTargetInfluences={nodes.Mineral_2.morphTargetInfluences}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/Mineral.glb");
