/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Color, Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Potion9_Filled_1: Mesh;
    Potion9_Filled_2: Mesh;
    Potion9_Filled_3: Mesh;
  };
  materials: {
    Glass: MeshStandardMaterial;
    Liquid_Green: MeshStandardMaterial;
    Brown: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/Potion9_Filled.glb"
  ) as unknown as GLTFResult;

  materials.Glass.transparent = true;
  materials.Glass.opacity = 0.5;
  materials.Liquid_Green.color = new Color("#00ff55");

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Potion9_Filled_1.geometry}
          material={materials.Glass}
        />
        <mesh
          geometry={nodes.Potion9_Filled_2.geometry}
          material={materials.Liquid_Green}
        />
        <mesh
          geometry={nodes.Potion9_Filled_3.geometry}
          material={materials.Brown}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/Potion9_Filled.glb");
