/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Sword_1: Mesh;
    Sword_2: Mesh;
    Sword_3: Mesh;
    Sword_4: Mesh;
    Sword_5: Mesh;
  };
  materials: {
    DarkSteel: MeshStandardMaterial;
    DarkWood: MeshStandardMaterial;
    LightWood: MeshStandardMaterial;
    LightSteel: MeshStandardMaterial;
    Steel: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/rpg_items_pack/Sword.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Sword_1.geometry}
          material={materials.DarkSteel}
        />
        <mesh geometry={nodes.Sword_2.geometry} material={materials.DarkWood} />
        <mesh
          geometry={nodes.Sword_3.geometry}
          material={materials.LightWood}
        />
        <mesh
          geometry={nodes.Sword_4.geometry}
          material={materials.LightSteel}
        />
        <mesh geometry={nodes.Sword_5.geometry} material={materials.Steel} />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/rpg_items_pack/Sword.glb");
