import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { TripRegion } from "../content/tripCentroids";

export type { TripRegion } from "../content/tripCentroids";

/** `[latitude, longitude]`, both rounded to 2 decimals (~1.1 km). */
export type GeoPointTuple = [lat: number, lng: number];

/** `[minLng, minLat, maxLng, maxLat]`, the GeoJSON bbox order. */
export type GeoBoundingBox = [minLng: number, minLat: number, maxLng: number, maxLat: number];

export type TripLocation = {
  /** Folder name under `assets/photography` — the `/photography/[tripName]` route slug. */
  name: string;
  /** Human readable label for the marker and the legend. */
  label: string;
  /** Coarse grouping for the globe legend. */
  region: TripRegion;
  /** Marker latitude: centroid of the EXIF points when trustworthy, else the manual pin. */
  lat: number;
  /** Marker longitude. */
  lng: number;
  /** Where `lat`/`lng` came from. */
  source: "exif" | "manual";
  /** Every image file in the folder. */
  photoCount: number;
  /**
   * Images carrying real EXIF GPS. This is the raw count; a handful of those points can
   * still be rejected as outliers and therefore be missing from `points`.
   */
  gpsCount: number;
  /** Bounds of the kept EXIF points. `null` whenever `source === "manual"`. */
  bbox: GeoBoundingBox | null;
  /**
   * Real EXIF positions only — never inferred ones. Rounded to 2 decimals and deduped,
   * in capture order. Empty for the folders whose cameras never wrote GPS.
   */
  points: GeoPointTuple[];
  /**
   * `"collection"` is a cross-trip curation, not a place: draw no pin, no label and no
   * legend swatch for it, and never count it as somewhere visited — its photos duplicate
   * the per-trip folders. Only `best-of` uses it today.
   */
  kind?: "collection";
  /**
   * A journey rather than a place. `points` are in chronological order and belong on the
   * globe as a great-circle polyline, not as a single pin. Only `transat` uses it today.
   */
  track?: boolean;
};

export type PhotoGeoTotals = {
  photos: number;
  withExifGps: number;
  trips: number;
};

export type PhotoGeoData = {
  trips: TripLocation[];
  totals: PhotoGeoTotals;
};

/** One closed coastline loop as `[lon, lat]` pairs — note the GeoJSON axis order. */
export type LandRing = [lon: number, lat: number][];

/**
 * The shape `buildWorldLandData.ts` writes. The browser reads this file through a plain
 * JSON import inside the globe's lazy chunk, so there is deliberately no fs reader here.
 */
export type WorldLandData = {
  rings: LandRing[];
};

let _photoGeoData: PhotoGeoData | null = null;

/**
 * Keep the argument a single string literal. `resolve(process.cwd(), ...segments)` reads
 * as a dynamic pattern to the Turbopack/NFT tracer, which then matched 22474 files and
 * traced the whole project into the page bundle. A literal resolves to the one file.
 *
 * A static `import` of the JSON would also silence the tracer, but it drags both files
 * into every module graph that touches this one — that alone pushed the PhotoGlobe unit
 * tests from 3s to a timeout.
 */
function readJson<T>(filePath: string): T {
  return JSON.parse(readFileSync(filePath, "utf-8")) as T;
}

/**
 * Per-trip marker positions and EXIF point clouds, generated by
 * `src/scripts/photography/extractPhotoGeodata.ts`. Build-time only: call it from
 * `getStaticProps` and pass the result down as a prop.
 */
export function getPhotoGeoData(): PhotoGeoData {
  if (_photoGeoData) return _photoGeoData;
  _photoGeoData = readJson<PhotoGeoData>(
    resolve(process.cwd(), "src/content/photo-locations.json"),
  );
  return _photoGeoData;
}

/** Trips that deserve a pin: everything except the `best-of` collection. */
export function getMarkerTrips(data: PhotoGeoData): TripLocation[] {
  return data.trips.filter((trip) => trip.kind !== "collection");
}

/**
 * Longitude/latitude to a point on a sphere.
 *
 * The land mesh AND the markers must both go through this function. If they use even
 * slightly different axis conventions every pin drifts off its coastline, and the bug
 * reads as bad geodata rather than bad math.
 *
 * Convention: +Y is the north pole, lon 0 points at +X, lon 90E points at -Z.
 * Returns a tuple so this module stays free of a three.js import — spread it into a
 * `Vector3` (`new Vector3(...latLngToVector3(lat, lng))`) or push it into a
 * `BufferAttribute` array directly.
 */
export function latLngToVector3(lat: number, lng: number, radius = 1): [number, number, number] {
  const phi = (lat * Math.PI) / 180;
  const lambda = (lng * Math.PI) / 180;
  const cosPhi = Math.cos(phi);
  return [
    radius * cosPhi * Math.cos(lambda),
    radius * Math.sin(phi),
    -radius * cosPhi * Math.sin(lambda),
  ];
}
