/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  GenericInstancedSystem,
  MeshMaterialCombos,
} from "@components/canvas/Trees/GenericInstancingSystem";
import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial, Vector3 } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    BirchTree_Dead_Snow_4_1: Mesh;
    BirchTree_Dead_Snow_4_2: Mesh;
    BirchTree_Dead_Snow_4_3: Mesh;
  };
  materials: {
    White: MeshStandardMaterial;
    Snow: MeshStandardMaterial;
    Black: MeshStandardMaterial;
  };
};

export function InstancedBirchTreeDeadSnow4({
  positions,
}: {
  positions: Vector3[];
}) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["BirchTree_Dead_Snow_4_1", "White"],
    ["BirchTree_Dead_Snow_4_2", "Snow"],
    ["BirchTree_Dead_Snow_4_3", "Black"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/BirchTree_Dead_Snow_4.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/BirchTree_Dead_Snow_4.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.BirchTree_Dead_Snow_4_1.geometry}
          material={materials.White}
        />
        <mesh
          geometry={nodes.BirchTree_Dead_Snow_4_2.geometry}
          material={materials.Snow}
        />
        <mesh
          geometry={nodes.BirchTree_Dead_Snow_4_3.geometry}
          material={materials.Black}
        />
      </group>
    </group>
  );
}
