/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  GenericInstancedSystem,
  MeshMaterialCombos,
} from "@components/canvas/InstancedMeshSystem/GenericInstancingSystem";
import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial, Vector3 } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Bush_Snow_1_1: Mesh;
    Bush_Snow_1_2: Mesh;
  };
  materials: {
    Snow: MeshStandardMaterial;
    Green: MeshStandardMaterial;
  };
};

export function InstancedBushSnow1({ positions }: { positions: Vector3[] }) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["Bush_Snow_1_1", "Snow"],
    ["Bush_Snow_1_2", "Green"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/Bush_Snow_1.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/Bush_Snow_1.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Bush_Snow_1_1.geometry}
          material={materials.Snow}
        />
        <mesh
          geometry={nodes.Bush_Snow_1_2.geometry}
          material={materials.Green}
        />
      </group>
    </group>
  );
}
