/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial, Vector3 } from "three";
import { GLTF } from "three-stdlib";
import {
  GenericInstancedSystem,
  MeshMaterialCombos,
} from "@components/canvas/Trees/GenericInstancingSystem";

type GLTFResult = GLTF & {
  nodes: {
    Bush_1: Mesh;
  };
  materials: {
    Green: MeshStandardMaterial;
  };
};

export function InstancedBush1({ positions }: { positions: Vector3[] }) {
  const meshMaterialCombos: MeshMaterialCombos = [["Bush_1", "Green"]];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/Bush_1.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/Bush_1.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Bush_1.geometry}
        material={materials.Green}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}
