/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  GenericInstancedSystem,
  MeshMaterialCombos,
} from "@components/canvas/Trees/GenericInstancingSystem";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial, Vector3 } from "three";

type GLTFResult = GLTF & {
  nodes: {
    CactusFlowers_2_1: Mesh;
    CactusFlowers_2_2: Mesh;
  };
  materials: {
    Green: MeshStandardMaterial;
    Pink: MeshStandardMaterial;
  };
};

export function InstancedCactusFlowers2({
  positions,
}: {
  positions: Vector3[];
}) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["CactusFlowers_2_1", "Green"],
    ["CactusFlowers_2_2", "Pink"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/CactusFlowers_2.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/CactusFlowers_2.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.CactusFlowers_2_1.geometry}
          material={materials.Green}
        />
        <mesh
          geometry={nodes.CactusFlowers_2_2.geometry}
          material={materials.Pink}
        />
      </group>
    </group>
  );
}
