/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  GenericInstancedSystem,
  MeshMaterialCombos,
} from "@components/canvas/InstancedMeshSystem/GenericInstancingSystem";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial, Vector3 } from "three";

type GLTFResult = GLTF & {
  nodes: {
    CommonTree_Dead_Snow_2_1: Mesh;
    CommonTree_Dead_Snow_2_2: Mesh;
  };
  materials: {
    Wood: MeshStandardMaterial;
    Snow: MeshStandardMaterial;
  };
};

export function InstancedCommonTreeDeadSnow2({
  positions,
}: {
  positions: Vector3[];
}) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["CommonTree_Dead_Snow_2_1", "Wood"],
    ["CommonTree_Dead_Snow_2_2", "Snow"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/CommonTree_Dead_Snow_2.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/CommonTree_Dead_Snow_2.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.CommonTree_Dead_Snow_2_1.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.CommonTree_Dead_Snow_2_2.geometry}
          material={materials.Snow}
        />
      </group>
    </group>
  );
}
