/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  GenericInstancedSystem,
  MeshMaterialCombos,
} from "@components/canvas/Trees/GenericInstancingSystem";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial, Vector3 } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Rock_Moss_7_1: Mesh;
    Rock_Moss_7_2: Mesh;
  };
  materials: {
    Green: MeshStandardMaterial;
    Rock: MeshStandardMaterial;
  };
};

export function InstancedRockMoss7({ positions }: { positions: Vector3[] }) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["Rock_Moss_7_1", "Green"],
    ["Rock_Moss_7_2", "Rock"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/Rock_Moss_7.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/Rock_Moss_7.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Rock_Moss_7_1.geometry}
          material={materials.Green}
        />
        <mesh
          geometry={nodes.Rock_Moss_7_2.geometry}
          material={materials.Rock}
        />
      </group>
    </group>
  );
}
