/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  GenericInstancedSystem,
  MeshMaterialCombos,
} from "@components/canvas/Trees/GenericInstancingSystem";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial, Vector3 } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Willow_Autumn_3_1: Mesh;
    Willow_Autumn_3_2: Mesh;
  };
  materials: {
    Wood: MeshStandardMaterial;
    Orange: MeshStandardMaterial;
  };
};

export function InstancedWillowAutumn3({
  positions,
}: {
  positions: Vector3[];
}) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["Willow_Autumn_3_1", "Wood"],
    ["Willow_Autumn_3_2", "Orange"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/Willow_Autumn_3.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/Willow_Autumn_3.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Willow_Autumn_3_1.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Willow_Autumn_3_2.geometry}
          material={materials.Orange}
        />
      </group>
    </group>
  );
}
