/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  GenericInstancedSystem,
  MeshMaterialCombos,
} from "@components/canvas/Trees/GenericInstancingSystem";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial, Vector3 } from "three";

type GLTFResult = GLTF & {
  nodes: {
    WoodLog_1: Mesh;
    WoodLog_2: Mesh;
    WoodLog_3: Mesh;
  };
  materials: {
    Wood: MeshStandardMaterial;
    Mushroom_Top: MeshStandardMaterial;
    Mushroom_Bottom: MeshStandardMaterial;
  };
};

export function InstancedWoodLog({ positions }: { positions: Vector3[] }) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["WoodLog_1", "Wood"],
    ["WoodLog_2", "Mushroom_Top"],
    ["WoodLog_3", "Mushroom_Bottom"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/WoodLog.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/WoodLog.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.WoodLog_1.geometry} material={materials.Wood} />
        <mesh
          geometry={nodes.WoodLog_2.geometry}
          material={materials.Mushroom_Top}
        />
        <mesh
          geometry={nodes.WoodLog_3.geometry}
          material={materials.Mushroom_Bottom}
        />
      </group>
    </group>
  );
}
