import bundleAnalyzer from "@next/bundle-analyzer";
import { generateRedirects } from "./src/scripts/createRedirects.js";

const isDev = process.argv.includes("dev") || process.env.NODE_ENV === "development";
const isBuild = process.argv.includes("build");
const veliteHmrFiles = [
  "sectionDescriptions.json",
  "posts.json",
  "newsletters.json",
  "booknotes.json",
  "pages.json",
  "podcastnotes.json",
  "travelblogs.json",
  "backlinks.json",
  "r3f-links.json",
];

async function writeVeliteHmrStamps(files) {
  const { mkdir, stat, writeFile } = await import("node:fs/promises");
  const { resolve } = await import("node:path");
  const stampDir = resolve(".velite/hmr");
  await mkdir(stampDir, { recursive: true });

  await Promise.all(
    files.map(async (file) => {
      const source = resolve(".velite", file);
      let mtimeMs = 0;
      let size = 0;
      try {
        const stats = await stat(source);
        mtimeMs = stats.mtimeMs;
        size = stats.size;
      } catch {}

      await writeFile(
        resolve(stampDir, file),
        JSON.stringify({ file, mtimeMs, size, updatedAt: Date.now() }),
      );
    }),
  );
}

// VELITE_STARTED guard only applies to dev (HMR may re-import next.config).
// Production builds always rebuild velite to avoid serving a stale/empty
// .velite cache from an earlier Vercel build.
const shouldRunVelite = isBuild || (isDev && !process.env.VELITE_STARTED);
if (shouldRunVelite) {
  if (isDev) process.env.VELITE_STARTED = "1";
  const { build } = await import("velite");
  await build({ watch: isDev, clean: !isDev, logLevel: "error" });

  // Generate R3F navigation links JSON (replaces next-plugin-preval)
  const { readdir, lstat, readFile, writeFile } = await import("node:fs/promises");
  const { resolve, join } = await import("node:path");
  const r3fDir = resolve("src/pages/r3f");
  const shaderDir = resolve("src/shaders/standaloneFragmentShaders");
  const toTitleCase = (s) =>
    s
      .split("-")
      .map((w) => w[0].toUpperCase() + w.slice(1))
      .join(" ");
  // Demos that exist as routes but aren't finished yet: keep them reachable by
  // direct URL for local iteration, but out of the nav (and the timeline).
  let hiddenR3fRoutes = new Set();
  try {
    const hidden = JSON.parse(
      await readFile(resolve("src/content/r3f-hidden-routes.json"), "utf-8"),
    );
    hiddenR3fRoutes = new Set(hidden.hidden);
  } catch {}
  const links = {};
  const dirs = (await readdir(r3fDir)).filter((f) => !f.includes(".tsx"));
  for (const dir of dirs) {
    if (dir === "shaders") continue;
    const dirPath = join(r3fDir, dir);
    if ((await lstat(dirPath)).isFile()) continue;
    const files = await readdir(dirPath);
    links[toTitleCase(dir)] = files
      .map((f) => f.replace(".tsx", ""))
      .map((name) => ({ name, url: `/r3f/${dir}/${name}` }))
      .filter(({ url }) => !hiddenR3fRoutes.has(url));
  }
  const shaders = (await readdir(shaderDir))
    .filter((f) => f.endsWith(".frag"))
    .map((f) => f.replace(".frag", ""));
  links["Shader Demos"] = shaders.map((name) => ({ name, url: `/r3f/shaders/${name}` }));
  await writeFile(resolve(".velite/r3f-links.json"), JSON.stringify({ links }));

  // Generate search index and backlinks from velite data
  const { execSync } = await import("node:child_process");
  try {
    execSync("npx tsx src/scripts/generateSearchIndex.ts", { stdio: "pipe" });
  } catch {}
  try {
    execSync("npx tsx src/scripts/generateBacklinks.ts", { stdio: "pipe" });
  } catch {}
  await writeVeliteHmrStamps(veliteHmrFiles);
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  allowedDevOrigins: ["127.0.0.1"],
  typescript: {
    // R3F model files (400+) have type incompatibilities with Three.js 0.183 + React 19.
    // These are runtime-safe (generated by gltfjsx) but the types don't align.
    ignoreBuildErrors: true,
  },
  // NOTE: `experimental.optimizeCss` (Critters) used to inline the whole
  // stylesheet here via inlineThreshold=200000, which is larger than the
  // compiled CSS, so Critters inlined everything and stripped the <link>.
  // Measured on prod it was a net loss and a correctness bug:
  //
  //   - The same ~120KB of raw CSS went into *every* page - around 70% of the
  //     median page's uncompressed HTML - with only ~29% of the rules used on
  //     any given page and zero cross-page reuse. HTML is served
  //     `max-age=0, must-revalidate`, so that block was re-downloaded on every
  //     full page load; the external stylesheet it replaced is served
  //     immutable/1yr and cached, so it costs one round trip on the first page
  //     of a session and nothing after that.
  //   - Inlining does not rewrite relative url(). KaTeX's @font-face srcs
  //     (../media/KaTeX_*.woff2) resolved against /_next/static/css/ before,
  //     and against the *page* URL after, so every KaTeX font 404'd and all
  //     math on the site rendered in fallback fonts.
  //
  // Keep the plain <link rel="stylesheet">. Re-measured since (Chrome, CDP
  // throttling, median of 9 runs, 460 prerendered pages):
  //
  //     booknote HTML    26.1KB -> 8.9KB brotli
  //     homepage HTML    45.8KB -> 28.2KB brotli
  //     whole corpus     13.0MB -> 5.0MB brotli   (what a full crawl costs)
  //
  // The one thing inlining did buy is a round trip on a COLD load, since the
  // CSS then arrives in the same response as the HTML: cold FCP is ~36ms worse
  // on cable, ~96ms on 4G, ~700ms on Fast 3G and ~2.5s on Slow 3G without it.
  // That is latency, not bytes, so shrinking the CSS will not recover it. Warm
  // loads (CSS already cached) are faster at every profile, and break-even is
  // ~6 hard page loads per visitor.
  //
  // Do NOT try to win that round trip back by putting Critters in
  // preload:'media' or 'swap' mode. That is what caused the late-load reflow
  // this config previously worked around: next-themes sets the theme class
  // from a script after SSR, so Critters cannot see the `.dark` rules when it
  // splits critical from deferred CSS. A render-blocking <link> cannot flash by
  // construction - verified 0 unstyled painted frames on the homepage, a
  // booknote, a photography gallery and an r3f demo at Slow 3G.
  turbopack: {
    rules: {
      "*.mp3": { loaders: ["url-loader"], as: "*.js" },
      "*.ogg": { loaders: ["url-loader"], as: "*.js" },
      "*.wav": { loaders: ["url-loader"], as: "*.js" },
      "*.glsl": { loaders: ["raw-loader"], as: "*.js" },
      "*.vs": { loaders: ["raw-loader"], as: "*.js" },
      "*.fs": { loaders: ["raw-loader"], as: "*.js" },
      "*.vert": { loaders: ["raw-loader"], as: "*.js" },
      "*.frag": { loaders: ["raw-loader"], as: "*.js" },
    },
  },
  images: {
    loader: "custom",
    loaderFile: "./image-loader.js",
  },
  redirects: customRedirects,
  async headers() {
    return [
      {
        // Everything except Next's dev-only asset directory. Next 16 serves
        // /_next/static/development/_clientMiddlewareManifest.js as
        // `application/json` while loading it in a <script> tag, so a blanket
        // `nosniff` makes the browser refuse to execute it:
        //   Refused to execute script from '…/_clientMiddlewareManifest.js'
        //   because its MIME type ('application/json') is not executable.
        // Production responses are unaffected — that path only exists in dev.
        source: "/((?!_next/static/development).*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
        ],
      },
    ];
  },
  webpack: (config, { isServer }) => {
    config.infrastructureLogging = {
      level: "error",
    };

    config.module.rules.push({
      test: /\.(ogg|mp3|wav|mpe?g)$/i,
      exclude: config.exclude,
      use: [
        {
          loader: "url-loader",
          options: {
            limit: config.inlineImageLimit,
            fallback: "file-loader",
            publicPath: `${config.assetPrefix}/_next/static/audio/`,
            outputPath: `${isServer ? "../" : ""}static/audio/`,
            name: "[name]-[hash].[ext]",
            esModule: config.esModule || false,
          },
        },
      ],
    });

    // shader support
    config.module.rules.push({
      test: /\.(glsl|vs|fs|vert|frag)$/,
      exclude: /(node_modules|withContext)/,
      use: ["raw-loader", "glslify-loader"],
    });

    return config;
  },
};

const withBundleAnalyzer = bundleAnalyzer({
  enabled: process.env.ANALYZE === "true",
});

export default withBundleAnalyzer(nextConfig);

async function customRedirects() {
  const redirects = await generateRedirects();
  return [
    ...redirects,
    // Exact "/newsletter" has to come first: the ":id*" rule below also matches
    // it with an empty id and resolves to "/newsletters/", which Next then
    // redirects again to "/newsletters" (trailingSlash is false). One hop, not two.
    {
      source: "/newsletter",
      destination: "/newsletters",
      permanent: true,
    },
    {
      source: "/newsletter/:id*",
      destination: "/newsletters/:id*",
      permanent: true,
    },
    {
      source: "/pages/:id*",
      destination: "/:id*",
      permanent: true,
    },
    {
      source: "/feed.xml",
      destination: "/rss.xml",
      permanent: true,
    },
    {
      source: "/posts/my-productivity-systems",
      destination: "/posts/my-productivity-system",
      permanent: true,
    },
    // Short links for key pages
    {
      source: "/plasmaball",
      destination: "/r3f/scenes/plasma-ball",
      permanent: true,
    },
    {
      source: "/plasma",
      destination: "/r3f/scenes/plasma-ball",
      permanent: true,
    },
    {
      source: "/plasma-ball",
      destination: "/r3f/scenes/plasma-ball",
      permanent: true,
    },
    {
      source: "/photos",
      destination: "/photography/best-of",
      permanent: true,
    },
    {
      source: "/needles",
      destination: "/needlestack",
      permanent: true,
    },
    {
      source: "/shader-art",
      destination: "/r3f/scenes/shader-art-demo",
      permanent: true,
    },
    {
      source: "/yellow",
      destination: "/posts/the-best-yellow",
      permanent: true,
    },
    {
      source: "/start",
      destination: "/start-here",
      permanent: true,
    },
    {
      source: "/support",
      destination: "/donate",
      permanent: true,
    },
    {
      source: "/everything",
      destination: "/timeline",
      permanent: true,
    },
  ];
}
