import { generateRedirects } from "./src/scripts/createRedirects.js";
import bundleAnalyzer from "@next/bundle-analyzer";

const isDev = process.argv.indexOf("dev") !== -1;
const isBuild = process.argv.indexOf("build") !== -1;
// VELITE_STARTED guard only applies to dev (HMR may re-import next.config).
// Production builds always rebuild velite to avoid serving a stale/empty
// .velite cache from an earlier Vercel build.
const shouldRunVelite = isBuild || (isDev && !process.env.VELITE_STARTED);
if (shouldRunVelite) {
  if (isDev) process.env.VELITE_STARTED = "1";
  const { build } = await import("velite");
  await build({ watch: isDev, clean: !isDev, logLevel: "error" });

  // Generate R3F navigation links JSON (replaces next-plugin-preval)
  const { readdir, lstat, writeFile } = await import("fs/promises");
  const { resolve, join } = await import("path");
  const r3fDir = resolve("src/pages/r3f");
  const shaderDir = resolve("src/shaders/standaloneFragmentShaders");
  const toTitleCase = (s) => s.split("-").map((w) => w[0].toUpperCase() + w.slice(1)).join(" ");
  const links = {};
  const dirs = (await readdir(r3fDir)).filter((f) => !f.includes(".tsx"));
  for (const dir of dirs) {
    if (dir === "shaders") continue;
    const dirPath = join(r3fDir, dir);
    if ((await lstat(dirPath)).isFile()) continue;
    const files = await readdir(dirPath);
    links[toTitleCase(dir)] = files.map((f) => f.replace(".tsx", "")).map((name) => ({ name, url: `/r3f/${dir}/${name}` }));
  }
  const shaders = (await readdir(shaderDir)).filter((f) => f.endsWith(".frag")).map((f) => f.replace(".frag", ""));
  links["Shader Demos"] = shaders.map((name) => ({ name, url: `/r3f/shaders/${name}` }));
  await writeFile(resolve(".velite/r3f-links.json"), JSON.stringify({ links }));

  // Generate search index and backlinks from velite data
  const { execSync } = await import("child_process");
  try {
    execSync("npx tsx src/scripts/generateSearchIndex.ts", { stdio: "pipe" });
  } catch {}
  try {
    execSync("npx tsx src/scripts/generateBacklinks.ts", { stdio: "pipe" });
  } catch {}
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  typescript: {
    // R3F model files (400+) have type incompatibilities with Three.js 0.183 + React 19.
    // These are runtime-safe (generated by gltfjsx) but the types don't align.
    ignoreBuildErrors: true,
  },
  turbopack: {
    rules: {
      "*.mp3": { loaders: ["url-loader"], as: "*.js" },
      "*.ogg": { loaders: ["url-loader"], as: "*.js" },
      "*.wav": { loaders: ["url-loader"], as: "*.js" },
      "*.glsl": { loaders: ["raw-loader"], as: "*.js" },
      "*.vs": { loaders: ["raw-loader"], as: "*.js" },
      "*.fs": { loaders: ["raw-loader"], as: "*.js" },
      "*.vert": { loaders: ["raw-loader"], as: "*.js" },
      "*.frag": { loaders: ["raw-loader"], as: "*.js" },
    },
  },
  images: {
    loader: "custom",
    loaderFile: "./image-loader.js",
  },
  redirects: customRedirects,
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
        ],
      },
    ];
  },
  webpack: (config, { isServer }) => {
    config.infrastructureLogging = {
      level: "error",
    };

    config.module.rules.push({
      test: /\.(ogg|mp3|wav|mpe?g)$/i,
      exclude: config.exclude,
      use: [
        {
          loader: "url-loader",
          options: {
            limit: config.inlineImageLimit,
            fallback: "file-loader",
            publicPath: `${config.assetPrefix}/_next/static/audio/`,
            outputPath: `${isServer ? "../" : ""}static/audio/`,
            name: "[name]-[hash].[ext]",
            esModule: config.esModule || false,
          },
        },
      ],
    });

    // shader support
    config.module.rules.push({
      test: /\.(glsl|vs|fs|vert|frag)$/,
      exclude: /(node_modules|withContext)/,
      use: ["raw-loader", "glslify-loader"],
    });

    return config;
  },
};

const withBundleAnalyzer = bundleAnalyzer({
  enabled: process.env.ANALYZE === "true",
});

export default withBundleAnalyzer(nextConfig);

async function customRedirects() {
  const redirects = await generateRedirects();
  return [
    ...redirects,
    {
      source: "/newsletter/:id*",
      destination: "/newsletters/:id*",
      permanent: true,
    },
    {
      source: "/pages/:id*",
      destination: "/:id*",
      permanent: true,
    },
    {
      source: "/feed.xml",
      destination: "/rss.xml",
      permanent: true,
    },
    {
      source: "/posts/my-productivity-systems",
      destination: "/posts/my-productivity-system",
      permanent: true,
    },
    // Short links for key pages
    {
      source: "/plasmaball",
      destination: "/r3f/scenes/plasma-ball",
      permanent: true,
    },
    {
      source: "/plasma",
      destination: "/r3f/scenes/plasma-ball",
      permanent: true,
    },
    {
      source: "/plasma-ball",
      destination: "/r3f/scenes/plasma-ball",
      permanent: true,
    },
    {
      source: "/photos",
      destination: "/photography/best-of",
      permanent: true,
    },
    {
      source: "/needles",
      destination: "/needlestack",
      permanent: true,
    },
    {
      source: "/shader-art",
      destination: "/r3f/scenes/shader-art-demo",
      permanent: true,
    },
    {
      source: "/yellow",
      destination: "/posts/the-best-yellow",
      permanent: true,
    },
    {
      source: "/start",
      destination: "/start-here",
      permanent: true,
    },
  ];
}
