import bundleAnalyzer from "@next/bundle-analyzer";
import { generateRedirects } from "./src/scripts/createRedirects.js";

const isDev = process.argv.includes("dev") || process.env.NODE_ENV === "development";
const isBuild = process.argv.includes("build");
// `pnpm dev` runs Velite in its own process (src/scripts/dev/watchVelite.ts)
// and sets VELITE_EXTERNAL=1. Building ~500 markdown files takes 15-40s of
// CPU; doing it here blocked every request to the Next server until it was
// done (plus ~10s of search index + backlinks), even when .velite already
// held usable data from the last run.
const veliteExternal = isDev && process.env.VELITE_EXTERNAL === "1";

// A .next/dev cache built for another Next version or config made Turbopack
// spawn PostCSS workers in a loop (thousands of processes). See the guard.
if (isDev) {
  const { clearStaleDevCache } = await import("./src/scripts/dev/devCacheGuard.mjs");
  clearStaleDevCache(import.meta.dirname);
}

// VELITE_STARTED guard only applies to dev (HMR may re-import next.config).
// Production builds always rebuild velite to avoid serving a stale/empty
// .velite cache from an earlier Vercel build.
const shouldRunVelite = isBuild || (isDev && !veliteExternal && !process.env.VELITE_STARTED);
if (shouldRunVelite) {
  if (isDev) process.env.VELITE_STARTED = "1";
  const { build } = await import("velite");
  await build({ watch: isDev, clean: !isDev, logLevel: "error" });

  const { generateR3fLinks, generateSearchIndexAndBacklinks, writeVeliteHmrStamp } = await import(
    "./src/scripts/veliteDerived.mjs"
  );
  await generateR3fLinks();
  await generateSearchIndexAndBacklinks();
  await writeVeliteHmrStamp();
} else if (veliteExternal) {
  // Only a clean checkout has no .velite output yet; wait for the first build
  // so pages and redirects do not fail on missing JSON.
  const { veliteHmrStampExists, veliteOutputExists, writeVeliteHmrStamp } = await import(
    "./src/scripts/veliteDerived.mjs"
  );
  if (!(await veliteOutputExists())) {
    console.log("  [velite] waiting for the first content build...");
    while (!(await veliteOutputExists())) {
      await new Promise((r) => setTimeout(r, 250));
    }
  }
  // loadVeliteData.ts imports the stamp statically, so it has to exist before
  // the first compile. Leave an existing one alone: rewriting it would refetch
  // getStaticProps in open tabs whenever Next reloads this config.
  if (!(await veliteHmrStampExists())) await writeVeliteHmrStamp();
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  allowedDevOrigins: ["127.0.0.1"],
  experimental: {
    // Back and forward return to the scroll position the page was left at,
    // instead of the top. src/lib/historyState.ts restores list filters to match.
    scrollRestoration: true,
  },
  typescript: {
    // R3F model files (400+) have type incompatibilities with Three.js 0.183 + React 19.
    // These are runtime-safe (generated by gltfjsx) but the types don't align.
    ignoreBuildErrors: true,
  },
  // NOTE: `experimental.optimizeCss` (Critters) used to inline the whole
  // stylesheet here via inlineThreshold=200000, which is larger than the
  // compiled CSS, so Critters inlined everything and stripped the <link>.
  // Measured on prod it was a net loss and a correctness bug:
  //
  //   - The same ~120KB of raw CSS went into *every* page - around 70% of the
  //     median page's uncompressed HTML - with only ~29% of the rules used on
  //     any given page and zero cross-page reuse. HTML is served
  //     `max-age=0, must-revalidate`, so that block was re-downloaded on every
  //     full page load; the external stylesheet it replaced is served
  //     immutable/1yr and cached, so it costs one round trip on the first page
  //     of a session and nothing after that.
  //   - Inlining does not rewrite relative url(). KaTeX's @font-face srcs
  //     (../media/KaTeX_*.woff2) resolved against /_next/static/css/ before,
  //     and against the *page* URL after, so every KaTeX font 404'd and all
  //     math on the site rendered in fallback fonts.
  //
  // Keep the plain <link rel="stylesheet">. Re-measured since (Chrome, CDP
  // throttling, median of 9 runs, 460 prerendered pages):
  //
  //     booknote HTML    26.1KB -> 8.9KB brotli
  //     homepage HTML    45.8KB -> 28.2KB brotli
  //     whole corpus     13.0MB -> 5.0MB brotli   (what a full crawl costs)
  //
  // The one thing inlining did buy is a round trip on a COLD load, since the
  // CSS then arrives in the same response as the HTML: cold FCP is ~36ms worse
  // on cable, ~96ms on 4G, ~700ms on Fast 3G and ~2.5s on Slow 3G without it.
  // That is latency, not bytes, so shrinking the CSS will not recover it. Warm
  // loads (CSS already cached) are faster at every profile, and break-even is
  // ~6 hard page loads per visitor.
  //
  // Do NOT try to win that round trip back by putting Critters in
  // preload:'media' or 'swap' mode. That is what caused the late-load reflow
  // this config previously worked around: next-themes sets the theme class
  // from a script after SSR, so Critters cannot see the `.dark` rules when it
  // splits critical from deferred CSS. A render-blocking <link> cannot flash by
  // construction - verified 0 unstyled painted frames on the homepage, a
  // booknote, a photography gallery and an r3f demo at Slow 3G.
  turbopack: {
    // Pin the root to this checkout. Agent worktrees live under
    // .claude/worktrees/ with their own lockfile, so Next otherwise infers the
    // parent repo as root and watches every sibling worktree.
    root: import.meta.dirname,
    rules: {
      "*.mp3": { loaders: ["url-loader"], as: "*.js" },
      "*.ogg": { loaders: ["url-loader"], as: "*.js" },
      "*.wav": { loaders: ["url-loader"], as: "*.js" },
      "*.glsl": { loaders: ["raw-loader"], as: "*.js" },
      "*.vs": { loaders: ["raw-loader"], as: "*.js" },
      "*.fs": { loaders: ["raw-loader"], as: "*.js" },
      "*.vert": { loaders: ["raw-loader"], as: "*.js" },
      "*.frag": { loaders: ["raw-loader"], as: "*.js" },
    },
  },
  images: {
    loader: "custom",
    loaderFile: "./image-loader.js",
  },
  async rewrites() {
    return {
      beforeFiles: [
        {
          source: "/api/img/:slug*",
          destination: "/api/local-image?slug=:slug*",
        },
      ],
    };
  },
  redirects: generateRedirects,
  async headers() {
    return [
      {
        // Everything except Next's dev-only asset directory. Next 16 serves
        // /_next/static/development/_clientMiddlewareManifest.js as
        // `application/json` while loading it in a <script> tag, so a blanket
        // `nosniff` makes the browser refuse to execute it:
        //   Refused to execute script from '…/_clientMiddlewareManifest.js'
        //   because its MIME type ('application/json') is not executable.
        // Production responses are unaffected — that path only exists in dev.
        source: "/((?!_next/static/development).*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
        ],
      },
    ];
  },
  webpack: (config, { isServer }) => {
    config.infrastructureLogging = {
      level: "error",
    };

    config.module.rules.push({
      test: /\.(ogg|mp3|wav|mpe?g)$/i,
      exclude: config.exclude,
      use: [
        {
          loader: "url-loader",
          options: {
            limit: config.inlineImageLimit,
            fallback: "file-loader",
            publicPath: `${config.assetPrefix}/_next/static/audio/`,
            outputPath: `${isServer ? "../" : ""}static/audio/`,
            name: "[name]-[hash].[ext]",
            esModule: config.esModule || false,
          },
        },
      ],
    });

    // shader support
    config.module.rules.push({
      test: /\.(glsl|vs|fs|vert|frag)$/,
      exclude: /(node_modules|withContext)/,
      use: ["raw-loader", "glslify-loader"],
    });

    return config;
  },
};

const withBundleAnalyzer = bundleAnalyzer({
  enabled: process.env.ANALYZE === "true",
});

export default withBundleAnalyzer(nextConfig);
