/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Arch_Door_1: Mesh;
    Arch_Door_2: Mesh;
    Arch_Door_3: Mesh;
    Arch_Door_4: Mesh;
  };
  materials: {
    DarkWood: MeshStandardMaterial;
    Metal: MeshStandardMaterial;
    DarkMetal: MeshStandardMaterial;
    Wood: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Arch_Door.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-1.2, 1.46, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      >
        <mesh
          geometry={nodes.Arch_Door_1.geometry}
          material={materials.DarkWood}
        />
        <mesh
          geometry={nodes.Arch_Door_2.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Arch_Door_3.geometry}
          material={materials.DarkMetal}
        />
        <mesh geometry={nodes.Arch_Door_4.geometry} material={materials.Wood} />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Arch_Door.glb");
