/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial, Mesh } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Arch_1: Mesh;
    Arch_2: Mesh;
    Arch_3: Mesh;
  };
  materials: {
    Wall_Dark: MeshStandardMaterial;
    Wall_Highlights: MeshStandardMaterial;
    Wall_Medium: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Arch.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Arch_1.geometry} material={materials.Wall_Dark} />
        <mesh
          geometry={nodes.Arch_2.geometry}
          material={materials.Wall_Highlights}
        />
        <mesh
          geometry={nodes.Arch_3.geometry}
          material={materials.Wall_Medium}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Arch.glb");
