/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial, Mesh } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Bag_Coins_1: Mesh;
    Bag_Coins_2: Mesh;
  };
  materials: {
    Bag: MeshStandardMaterial;
    Gold: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Bag_Coins.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Bag_Coins_1.geometry} material={materials.Bag} />
        <mesh geometry={nodes.Bag_Coins_2.geometry} material={materials.Gold} />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Bag_Coins.glb");
