/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Banner_wall_1: Mesh;
    Banner_wall_2: Mesh;
    Banner_wall_3: Mesh;
  };
  materials: {
    Metal: MeshStandardMaterial;
    Wood: MeshStandardMaterial;
    Main: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Banner_wall.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Banner_wall_1.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Banner_wall_2.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Banner_wall_3.geometry}
          material={materials.Main}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Banner_wall.glb");
