/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Banner_1: Mesh;
    Banner_2: Mesh;
    Banner_3: Mesh;
    Banner_4: Mesh;
  };
  materials: {
    Metal: MeshStandardMaterial;
    Wood: MeshStandardMaterial;
    Main: MeshStandardMaterial;
    DarkMetal: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Banner.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Banner_1.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Banner_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Banner_3.geometry} material={materials.Main} />
        <mesh
          geometry={nodes.Banner_4.geometry}
          material={materials.DarkMetal}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Banner.glb");
