/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Bucket_1: Mesh;
    Bucket_2: Mesh;
    Bucket_3: Mesh;
  };
  materials: {
    Wood: MeshStandardMaterial;
    DarkMetal: MeshStandardMaterial;
    Metal: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Bucket.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Bucket_1.geometry} material={materials.Wood} />
        <mesh
          geometry={nodes.Bucket_2.geometry}
          material={materials.DarkMetal}
        />
        <mesh geometry={nodes.Bucket_3.geometry} material={materials.Metal} />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Bucket.glb");
