/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Chest_Base_1: Mesh;
    Chest_Base_2: Mesh;
    Chest_Base_3: Mesh;
    Chest_Base_4: Mesh;
    Chest_Top_1: Mesh;
    Chest_Top_2: Mesh;
  };
  materials: {
    DarkWood: MeshStandardMaterial;
    Wood: MeshStandardMaterial;
    Metal: MeshStandardMaterial;
    Gold: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Chest_Gold.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Chest_Base_1.geometry}
          material={materials.DarkWood}
        />
        <mesh
          geometry={nodes.Chest_Base_2.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Chest_Base_3.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Chest_Base_4.geometry}
          material={materials.Gold}
        />
      </group>
      <group position={[0, 0.52, -0.35]} rotation={[2.1, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Chest_Top_1.geometry}
          material={materials.DarkWood}
        />
        <mesh geometry={nodes.Chest_Top_2.geometry} material={materials.Wood} />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Chest_Gold.glb");
