/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Decorative_Wall_1: Mesh;
    Decorative_Wall_2: Mesh;
  };
  materials: {
    Wall_Dark: MeshStandardMaterial;
    Wall_Highlights: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Decorative_Wall.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Decorative_Wall_1.geometry}
          material={materials.Wall_Dark}
        />
        <mesh
          geometry={nodes.Decorative_Wall_2.geometry}
          material={materials.Wall_Highlights}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Decorative_Wall.glb");
