/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Sword_WallMount: THREE.Mesh;
    Sword_1: THREE.Mesh;
    Sword_2: THREE.Mesh;
    Sword_3: THREE.Mesh;
    Sword_4: THREE.Mesh;
    Sword_5: THREE.Mesh;
    Sword_big_1: THREE.Mesh;
    Sword_big_2: THREE.Mesh;
    Sword_big_3: THREE.Mesh;
    Sword_big_4: THREE.Mesh;
    Sword_big_5: THREE.Mesh;
  };
  materials: {
    DarkWood: THREE.MeshStandardMaterial;
    DarkSteel: THREE.MeshStandardMaterial;
    ["DarkWood.001"]: THREE.MeshStandardMaterial;
    LightWood: THREE.MeshStandardMaterial;
    LightSteel: THREE.MeshStandardMaterial;
    Steel: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Sword_WallMount.glb"
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Sword_WallMount} />
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Sword_WallMount.glb");
