/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Sword_WallMount: Mesh;
    Sword_1: Mesh;
    Sword_2: Mesh;
    Sword_3: Mesh;
    Sword_4: Mesh;
    Sword_5: Mesh;
    Sword_big_1: Mesh;
    Sword_big_2: Mesh;
    Sword_big_3: Mesh;
    Sword_big_4: Mesh;
    Sword_big_5: Mesh;
  };
  materials: {
    DarkWood: MeshStandardMaterial;
    DarkSteel: MeshStandardMaterial;
    ["DarkWood.001"]: MeshStandardMaterial;
    LightWood: MeshStandardMaterial;
    LightSteel: MeshStandardMaterial;
    Steel: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Sword_WallMount.glb"
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Sword_WallMount} />
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Sword_WallMount.glb");
