/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Table_Big_1: Mesh;
    Table_Big_2: Mesh;
    Table_Big_3: Mesh;
  };
  materials: {
    Wood: MeshStandardMaterial;
    DarkMetal: MeshStandardMaterial;
    DarkWood: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Table_Big.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Table_Big_1.geometry} material={materials.Wood} />
        <mesh
          geometry={nodes.Table_Big_2.geometry}
          material={materials.DarkMetal}
        />
        <mesh
          geometry={nodes.Table_Big_3.geometry}
          material={materials.DarkWood}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Table_Big.glb");
