/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Trapdoor_open_1: Mesh;
    Trapdoor_open_2: Mesh;
    Trapdoor_open_3: Mesh;
    Trapdoor_open_4: Mesh;
  };
  materials: {
    Metal: MeshStandardMaterial;
    DarkMetal: MeshStandardMaterial;
    DarkWood: MeshStandardMaterial;
    Wood: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Trapdoor_open.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Trapdoor_open_1.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Trapdoor_open_2.geometry}
          material={materials.DarkMetal}
        />
        <mesh
          geometry={nodes.Trapdoor_open_3.geometry}
          material={materials.DarkWood}
        />
        <mesh
          geometry={nodes.Trapdoor_open_4.geometry}
          material={materials.Wood}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Trapdoor_open.glb");
