/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Trap_spikes_1: Mesh;
    Trap_spikes_2: Mesh;
  };
  materials: {
    Metal: MeshStandardMaterial;
    DarkMetal: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Trap_spikes.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Trap_spikes_1.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Trap_spikes_2.geometry}
          material={materials.DarkMetal}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Trap_spikes.glb");
