/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    WoodFire_1: Mesh;
    WoodFire_2: Mesh;
    WoodFire_3: Mesh;
  };
  materials: {
    DarkWood: MeshStandardMaterial;
    Wood: MeshStandardMaterial;
    Fire: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/modular_dungeon_1/Woodfire.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.WoodFire_1.geometry}
          material={materials.DarkWood}
        />
        <mesh geometry={nodes.WoodFire_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.WoodFire_3.geometry} material={materials.Fire} />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/modular_dungeon_1/Woodfire.glb");
