// Editorial themes layer for the /categories page and /themes/[slug] landings.
// Source of truth for theme membership, tag canonicalization, and drop list.
// Curated from .scratch/themes-plan.json (subagent editorial pass).

export type Theme = {
  slug: string;
  title: string;
  oneliner: string;
  tagMembers: string[];
  contentTypeFallback?: string[];
  hero: { src: string; alt: string };
};

export const themes: Theme[] = [
  {
    slug: "ai-frontier",
    title: "The AI Frontier",
    oneliner: "Weekly notes on the labs, models, and moments shaping artificial intelligence.",
    tagMembers: [
      "ai",
      "openai",
      "anthropic",
      "deepmind",
      "nvidia",
      "meta",
      "google",
      "microsoft",
      "agi",
      "llms",
      "machine learning",
      "generative ai",
      "image generation",
      "video generation",
      "robotics",
      "neuralink",
      "chatgpt",
      "alignment",
      "sam altman",
      "jensen huang",
      "elon musk",
      "mark zuckerberg",
      "spacex",
      "3d-generation",
      "deepfakes",
      "chips",
      "vr",
      "quantum computing",
    ],
    contentTypeFallback: ["Newsletter"],
    hero: {
      src: "/assets/blog/open-ai-avatar.png",
      alt: "OpenAI logo on a dark backdrop",
    },
  },
  {
    slug: "mind-and-meaning",
    title: "Mind & Meaning",
    oneliner: "Psychology, neuroscience, and the long human project of understanding ourselves.",
    tagMembers: [
      "psychology",
      "neuroscience",
      "consciousness",
      "philosophy",
      "sociology",
      "happiness",
      "motivation",
      "learning",
      "intelligence",
    ],
    hero: {
      src: "/assets/blog/brain.jpg",
      alt: "an illustration of a human brain",
    },
  },
  {
    slug: "living-well",
    title: "Living Well",
    oneliner: "Notes from a life of habits, focus, and figuring out what actually matters.",
    tagMembers: [
      "self-help",
      "good-life",
      "habits",
      "productivity",
      "wisdom",
      "advice",
      "happiness",
      "minimalism",
      "health",
      "life",
      "spirituality",
      "buddhism",
      "stoicism",
      "taoism",
    ],
    hero: {
      src: "/assets/blog/morning.jpg",
      alt: "a quiet morning routine scene",
    },
  },
  {
    slug: "reading-life",
    title: "A Reading Life",
    oneliner: "Books I underline, dog-ear, and keep coming back to — from fiction to philosophy.",
    tagMembers: [
      "non-fiction",
      "fiction",
      "fantasy",
      "sci-fi",
      "top-50",
      "made-me-think",
      "ideas",
      "curiosity",
      "reading",
    ],
    contentTypeFallback: ["Booknote"],
    hero: {
      src: "/assets/book-covers/navalmanack.jpg",
      alt: "the cover of The Almanack of Naval Ravikant",
    },
  },
  {
    slug: "on-the-road",
    title: "On the Road",
    oneliner: "Photo essays and field notes from islands, mountains, and the spaces between.",
    tagMembers: [
      "travel",
      "adventure",
      "hiking",
      "waterfall",
      "surfing",
      "relaxing",
      "dominica",
      "caribbean",
      "colombia",
      "guadeloupe",
      "martinique",
    ],
    contentTypeFallback: ["Travelblog"],
    hero: {
      src: "/assets/blog/laos-rice-field.jpg",
      alt: "a rice field at golden hour in Laos",
    },
  },
  {
    slug: "making-things",
    title: "Making Things",
    oneliner: "Creative coding, 3D, shaders, and the craft of building strange visual systems.",
    tagMembers: ["programming", "engineering", "design", "art", "music", "beauty"],
    hero: {
      src: "/assets/blog/fractal-garden.png",
      alt: "a colorful procedural fractal garden",
    },
  },
  {
    slug: "science-and-nature",
    title: "Science & Nature",
    oneliner: "Where biology, physics, and curiosity collide — the universe still rewards looking.",
    tagMembers: [
      "science",
      "biology",
      "biochemistry",
      "biotech",
      "evolution",
      "physics",
      "mathematics",
      "nanotechnology",
      "superconductors",
      "computation",
    ],
    hero: {
      src: "/assets/blog/mandelbrot.jpg",
      alt: "a Mandelbrot set rendered in deep colors",
    },
  },
  {
    slug: "future-arriving",
    title: "How the Future Arrives",
    oneliner: "Long arcs: progress, technology, and the shape of what comes next.",
    tagMembers: [
      "future",
      "progress",
      "technology",
      "business",
      "economics",
      "politics",
      "history",
      "infrastructure",
      "spacex",
    ],
    hero: {
      src: "/assets/blog/road.jpg",
      alt: "a long road disappearing into the horizon",
    },
  },
  {
    slug: "personal-essays",
    title: "Personal Essays",
    oneliner: "Slower writing on flow, decisions, and the strange business of being alive.",
    tagMembers: ["personal development"],
    contentTypeFallback: ["Post"],
    hero: {
      src: "/assets/blog/keyboard.jpg",
      alt: "a worn keyboard ready for writing",
    },
  },
  {
    slug: "first-principles",
    title: "First Principles",
    oneliner: "Math, computation, and the conceptual bedrock under the rest of the site.",
    tagMembers: ["mathematics", "programming", "computation", "physics", "engineering"],
    hero: {
      src: "/assets/blog/vector-demo.png",
      alt: "an animated diagram of vector arithmetic",
    },
  },
];

// Merge variants and near-synonyms to a single canonical form.
// Source of truth lives here until the markdown frontmatter is rewritten.
export const canonicalMap: Record<string, string> = {
  "3d manipulation": "3d-generation",
  aging: "health",
  "ai alignment": "alignment",
  "ai applications": "ai",
  "ai development": "ai",
  "ai ethics": "alignment",
  "ai safety": "alignment",
  algorithms: "programming",
  "alignment research": "alignment",
  "apple vision pro": "vr",
  ar: "vr",
  "art-of-living": "good-life",
  "artificial general intelligence": "agi",
  "artificial intelligence": "ai",
  asi: "agi",
  astribot: "robotics",
  attention: "neuroscience",
  audiobox: "music",
  behavior: "psychology",
  biotechnology: "biotech",
  bogotá: "colombia",
  book: "reading",
  booknotes: "reading",
  brain: "neuroscience",
  "brain-reading": "neuroscience",
  brain2music: "neuroscience",
  brainmap: "neuroscience",
  "cell atlas": "biology",
  cells: "biology",
  classics: "reading",
  "clone robotics": "robotics",
  "cloud computing": "infrastructure",
  cognition: "neuroscience",
  "computer science": "programming",
  connectome: "neuroscience",
  "cortical labs": "neuroscience",
  "data transfer": "infrastructure",
  "deep fakes": "deepfakes",
  development: "programming",
  "diffusion-models": "diffusion models",
  "distributed-training": "infrastructure",
  dopamine: "neuroscience",
  dystopia: "fiction",
  eastern: "spirituality",
  economy: "economics",
  elon: "elon musk",
  "emotional health": "health",
  enzymes: "biochemistry",
  epistemology: "philosophy",
  exercise: "health",
  "existential risk": "alignment",
  "figure 02": "robotics",
  "figure 1": "robotics",
  figure: "robotics",
  finances: "finance",
  "foundation model": "machine learning",
  "free will": "philosophy",
  fruitfly: "biology",
  "fully body haptics": "vr",
  futurism: "future",
  genai: "generative ai",
  "general ai": "agi",
  "generative-ai": "generative ai",
  genes: "biology",
  "good life": "good-life",
  "great-ideas": "ideas",
  guadelouope: "guadeloupe",
  "how to live": "good-life",
  "human nature": "psychology",
  "image editing": "image generation",
  immunology: "biology",
  "intelligence-explosion": "agi",
  "jam session": "music",
  "la paz": "bolivia",
  "life advice": "good-life",
  "lk-99": "superconductors",
  llm: "llms",
  lltm: "llms",
  lltms: "llms",
  longevity: "health",
  "machine learning (ml)": "machine learning",
  "made-you-think": "made-me-think",
  "marc zuckerberg": "mark zuckerberg",
  masterpiece: "top-50",
  meaning: "philosophy",
  medicine: "health",
  meditation: "spirituality",
  "mental-models": "ideas",
  metaai: "meta",
  metaverse: "vr",
  midjourney: "image generation",
  mind: "psychology",
  mindset: "self-help",
  "molecular biology": "biochemistry",
  morality: "philosophy",
  "music-fx": "music",
  musk: "elon musk",
  mutations: "biology",
  nano: "nanotechnology",
  "nano-tech": "nanotechnology",
  "nano-technology": "nanotechnology",
  "natural language processing (nlp)": "machine learning",
  "neural networks": "machine learning",
  "neuron computer": "neuroscience",
  "nomadic minimalism": "minimalism",
  novel: "fiction",
  nutrition: "health",
  office: "work",
  "open ai": "openai",
  "open-ai": "openai",
  optimus: "robotics",
  painting: "art",
  "paradigm-shift": "ideas",
  "personal development": "self-help",
  "pop-science": "science",
  protein: "biochemistry",
  proteins: "biochemistry",
  "quantum-physics": "physics",
  reason: "philosophy",
  "reinforcement learning": "machine learning",
  reinforcement: "machine learning",
  "remote work": "work",
  "reversible computing": "computation",
  robocasa: "robotics",
  robots: "robotics",
  "robust robotics": "robotics",
  "science-fiction": "sci-fi",
  "self help": "self-help",
  "self-improvement": "self-help",
  singularity: "agi",
  sleep: "health",
  software: "programming",
  "space exploration": "spacex",
  "spatial computing": "vr",
  "stability ai": "stabilityai",
  "stable diffusion": "image generation",
  starship: "spacex",
  "start ups": "business",
  stoic: "stoicism",
  "success-literature": "self-help",
  superconductor: "superconductors",
  supplements: "health",
  "tango create": "3d-generation",
  tech: "technology",
  "text to 3d": "3d-generation",
  "text-to-video": "video generation",
  "the-best": "top-50",
  "thought-provoking": "made-me-think",
  traveling: "travel",
  v2a: "video generation",
  "video to audio": "video generation",
  waterfalls: "waterfall",
  xenobots: "biology",
  "zero-th principle thinking": "ideas",
};

// Tags treated as noise — brand singletons, conference names, individual names,
// stray descriptors. Removed during canonicalization.
export const droppedTags: Set<string> = new Set([
  "3b1b",
  "a16z",
  "adam savage",
  "ai crawlers",
  "ai marketplace",
  "ai porn",
  "ai research",
  "ai search",
  "aidan mclaughlin",
  "ais",
  "alphachip",
  "ancient",
  "andrej karpathy",
  "animation",
  "answer.ai",
  "applications builder",
  "arc institute",
  "arrangements",
  "array labs",
  "aws",
  "barcelona",
  "bard",
  "beach",
  "bicycle",
  "biden",
  "biography",
  "biosecurity",
  "black",
  "black forest labs",
  "brainwave",
  "breakthrough",
  "bridge",
  "bruce booth",
  "capitalism",
  "carpentopod",
  "cascade aux ecrevisses",
  "casey handmer",
  "ccc",
  "cerebras",
  "character",
  "chatbot",
  "chatbots",
  "christians home",
  "claude 3.7",
  "claude code",
  "claude sonnet",
  "colors",
  "communication",
  "computex",
  "computing",
  "context-window",
  "cosine",
  "crowdstrike",
  "cyberpunk",
  "cycling",
  "dalle-3",
  "dataset",
  "davos",
  "derek sivers",
  "devin",
  "dewave",
  "diatom",
  "diatoms",
  "dreammachine",
  "dwarkesh patel",
  "earth ai",
  "ed zitron",
  "edify",
  "egoism",
  "emu",
  "enveda",
  "eureka labs",
  "experience design",
  "extropic",
  "falls",
  "farm",
  "feminism",
  "feynman",
  "firefly video",
  "fireship",
  "flow",
  "flux",
  "forest",
  "fugatto",
  "game engines",
  "game-engine",
  "gemini",
  "gen3",
  "gene kim",
  "genie",
  "german",
  "gibberlink",
  "github",
  "github universe",
  "goldilocks zone",
  "google i/o",
  "google keynote",
  "gpt",
  "gpt-4",
  "gpt-4-o",
  "gpt-store",
  "grapes",
  "greeks",
  "grok",
  "heygen",
  "hitchhiking",
  "how-to",
  "huberman-lab",
  "human level tennis playing robot",
  "ilya sutskever",
  "improvement",
  "inflection",
  "interactive avatars",
  "interconnects",
  "international math olympiad",
  "interview",
  "island",
  "javier-milei",
  "jetson orin nano",
  "joscha bach",
  "kara swisher",
  "kasra",
  "keynote",
  "klarna",
  "kling",
  "la souffleur",
  "labs",
  "laion",
  "latin",
  "leopold aschenbrenner",
  "lifescivc",
  "llama",
  "llama 3",
  "llama2",
  "love",
  "lumalabs",
  "machines of loving grace",
  "madrid",
  "mango",
  "mars",
  "mazeau fall",
  "meshy",
  "michael levin",
  "microscopy",
  "mining",
  "mira murati",
  "mit",
  "morocco",
  "moviegen",
  "multimodal",
  "nature",
  "news",
  "newsletter",
  "notboring",
  "notebooklm",
  "nvidia gtc",
  "o1",
  "open source",
  "orion",
  "os-copilot",
  "papers",
  "paul graham",
  "peace",
  "photography",
  "plage du bosco",
  "port luis",
  "post-truth",
  "practical",
  "procrastination",
  "prophetic-ai",
  "protein printer",
  "reality",
  "reasoning",
  "rendering text",
  "replit",
  "research",
  "river",
  "river bridge",
  "robert sapolsky",
  "routine",
  "runwayml",
  "safe superintelligence inc",
  "sakana",
  "sakana ai",
  "sam 2",
  "sapiens",
  "saut de lezarde",
  "scientist",
  "search gpt",
  "sebastian lague",
  "segmentation",
  "simulation",
  "simulon",
  "single photon cameras",
  "situational awareness",
  "sora",
  "soufriere",
  "space travel",
  "spain",
  "starlink",
  "sundar pichai",
  "sunlight",
  "sunset",
  "synthetic consciousness",
  "techno authoritarianism",
  "techno-optimism",
  "tesla",
  "testing",
  "the rot economy",
  "tikazalou",
  "trafalgar",
  "translation",
  "trump",
  "tutorial",
  "vaire",
  "veo2",
  "video",
  "violence",
  "wan 2.1",
  "whisk",
  "willow",
  "world-models",
  "writing",
  "wwdc",
  "xai",
  "zuberlin",
]);

export function canonicalizeTags(raw: string | undefined | null): string[] {
  if (!raw) return [];
  const tags = raw
    .split(",")
    .map((t) => t.trim().toLowerCase())
    .filter(Boolean);
  const out = new Set<string>();
  for (const tag of tags) {
    if (canonicalMap[tag]) {
      out.add(canonicalMap[tag]);
      continue;
    }
    if (droppedTags.has(tag)) continue;
    out.add(tag);
  }
  return [...out];
}
