/**
 * Advisory coverage report: routes nothing links to, and indexable routes the
 * sitemap forgot. Both were Ahrefs findings (/photography/spain-2024 and
 * /categories had no inlinks), and both are judgement calls rather than bugs —
 * some routes are deliberately unlinked — so this never fails the build.
 *
 * Inlinks are read out of the prerendered HTML instead of the sources, because
 * most real links are generated by a listing component from an interpolated
 * href that the static extractor cannot resolve.
 */

import { existsSync, readFileSync } from "node:fs";
import { relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { glob } from "glob";
import { normalizeRoute, PUBLIC_DIR, ROOT } from "./references";
import { PAGES_DIR, type Routes } from "./routes";

const HTML_HREF = /href="([^"]+)"/g;
const SITEMAP_LOC = /<loc>([^<]+)<\/loc>/g;
const NOINDEX = /<meta name="robots" content="noindex/;

/** Routes that are infrastructure, not pages a reader can arrive at. */
const NEVER_LINKED = new Set(["/", "/404", "/500"]);

async function loadSitemapExclusions(): Promise<Set<string>> {
  const excluded = new Set<string>();
  try {
    const configPath = pathToFileURL(resolve(ROOT, "next-sitemap.config.js")).href;
    const config = (await import(/* @vite-ignore */ configPath)) as {
      default?: { exclude?: string[] };
    };
    for (const entry of config.default?.exclude ?? []) excluded.add(entry);
  } catch {
    // Config unreadable — report everything rather than silently under-reporting.
  }
  try {
    const hidden = JSON.parse(
      readFileSync(resolve(ROOT, "src/content/r3f-hidden-routes.json"), "utf-8"),
    ) as { hidden?: string[] };
    for (const entry of hidden.hidden ?? []) excluded.add(entry);
  } catch {}
  return excluded;
}

function routeOfHtml(file: string): string {
  const path = `/${relative(PAGES_DIR, file).replace(/\.html$/, "")}`;
  return path === "/index" ? "/" : path;
}

export type Coverage = {
  orphans: string[];
  missingFromSitemap: string[];
  sitemapEntries: number;
};

export async function collectCoverage(routes: Routes): Promise<Coverage | undefined> {
  if (!existsSync(PAGES_DIR)) return undefined;

  const html = await glob("**/*.html", { cwd: PAGES_DIR, absolute: true, nodir: true });

  const linked = new Set<string>();
  const noindex = new Set<string>();
  for (const file of html) {
    const source = readFileSync(file, "utf-8");
    if (NOINDEX.test(source)) noindex.add(routeOfHtml(file));
    HTML_HREF.lastIndex = 0;
    let match = HTML_HREF.exec(source);
    while (match !== null) {
      const href = match[1].replace(/&#x2F;/g, "/").replace(/&amp;/g, "&");
      if (href.startsWith("/")) {
        const path = normalizeRoute(href);
        if (path) linked.add(path);
      }
      match = HTML_HREF.exec(source);
    }
  }

  const sitemap = new Set<string>();
  const sitemapPath = resolve(PUBLIC_DIR, "sitemap.xml");
  if (existsSync(sitemapPath)) {
    const xml = readFileSync(sitemapPath, "utf-8");
    SITEMAP_LOC.lastIndex = 0;
    let match = SITEMAP_LOC.exec(xml);
    while (match !== null) {
      const path = normalizeRoute(new URL(match[1]).pathname);
      if (path) sitemap.add(path);
      match = SITEMAP_LOC.exec(xml);
    }
  }

  const excluded = await loadSitemapExclusions();
  const pages = [...routes.exact].filter(
    (path) => !path.startsWith("/api/") && !NEVER_LINKED.has(path),
  );

  const orphans = pages.filter((path) => !linked.has(path)).sort();
  const missingFromSitemap = pages
    .filter(
      (path) => !sitemap.has(path) && !excluded.has(path) && !noindex.has(path) && sitemap.size > 0,
    )
    .sort();

  return { orphans, missingFromSitemap, sitemapEntries: sitemap.size };
}
