/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import {
  GenericInstancedSystem,
  type MeshMaterialCombos,
} from "src/canvas/InstancedMeshSystem/GenericInstancingSystem";
import type { Mesh, MeshStandardMaterial, Vector3 } from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    CommonTree_Dead_Snow_4_1: Mesh;
    CommonTree_Dead_Snow_4_2: Mesh;
  };
  materials: {
    Wood: MeshStandardMaterial;
    Snow: MeshStandardMaterial;
  };
};

export function InstancedCommonTreeDeadSnow4({
  positions,
}: {
  positions: Vector3[];
}) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["CommonTree_Dead_Snow_4_1", "Wood"],
    ["CommonTree_Dead_Snow_4_2", "Snow"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/CommonTree_Dead_Snow_4.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/CommonTree_Dead_Snow_4.glb",
  ) as unknown as unknown as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.CommonTree_Dead_Snow_4_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.CommonTree_Dead_Snow_4_2.geometry} material={materials.Snow} />
      </group>
    </group>
  );
}
