/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import {
  GenericInstancedSystem,
  type MeshMaterialCombos,
} from "src/canvas/InstancedMeshSystem/GenericInstancingSystem";
import type { Mesh, MeshStandardMaterial, Vector3 } from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    CommonTree_1_1: Mesh;
    CommonTree_1_2: Mesh;
  };
  materials: {
    Wood: MeshStandardMaterial;
    Green: MeshStandardMaterial;
  };
};

export function useTree1() {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/CommonTree_1.glb",
  ) as unknown as unknown as unknown as GLTFResult;
  return { nodes, materials };
}

export function InstancedCommonTree1({ positions }: { positions: Vector3[] }) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["CommonTree_1_1", "Wood"],
    ["CommonTree_1_2", "Green"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/CommonTree_1.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/CommonTree_1.glb",
  ) as unknown as unknown as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.CommonTree_1_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.CommonTree_1_2.geometry} material={materials.Green} />
      </group>
    </group>
  );
}
