/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  GenericInstancedSystem,
  MeshMaterialCombos,
} from "src/canvas/InstancedMeshSystem/GenericInstancingSystem";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial, Vector3 } from "three";

type GLTFResult = GLTF & {
  nodes: {
    PalmTree_4_1: Mesh;
    PalmTree_4_2: Mesh;
    PalmTree_4_3: Mesh;
    PalmTree_4_4: Mesh;
  };
  materials: {
    Wood: MeshStandardMaterial;
    Green: MeshStandardMaterial;
    DarkGreen: MeshStandardMaterial;
    Coconuts: MeshStandardMaterial;
  };
};

export function InstancedPalmTree4({ positions }: { positions: Vector3[] }) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["PalmTree_4_1", "Wood"],
    ["PalmTree_4_2", "Green"],
    ["PalmTree_4_3", "DarkGreen"],
    ["PalmTree_4_4", "Coconuts"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/PalmTree_4.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/PalmTree_4.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.PalmTree_4_1.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.PalmTree_4_2.geometry}
          material={materials.Green}
        />
        <mesh
          geometry={nodes.PalmTree_4_3.geometry}
          material={materials.DarkGreen}
        />
        <mesh
          geometry={nodes.PalmTree_4_4.geometry}
          material={materials.Coconuts}
        />
      </group>
    </group>
  );
}
