/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import {
  GenericInstancedSystem,
  type MeshMaterialCombos,
} from "src/canvas/InstancedMeshSystem/GenericInstancingSystem";
import type { Mesh, MeshStandardMaterial, Vector3 } from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    PineTree_Autumn_3_1: Mesh;
    PineTree_Autumn_3_2: Mesh;
    PineTree_Autumn_3_3: Mesh;
  };
  materials: {
    Wood: MeshStandardMaterial;
    Orange: MeshStandardMaterial;
    LightOrange: MeshStandardMaterial;
  };
};

export function InstancedPineTreeAutumn3({
  positions,
}: {
  positions: Vector3[];
}) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["PineTree_Autumn_3_1", "Wood"],
    ["PineTree_Autumn_3_2", "Orange"],
    ["PineTree_Autumn_3_3", "LightOrange"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/PineTree_Autumn_3.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/PineTree_Autumn_3.glb",
  ) as unknown as unknown as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.PineTree_Autumn_3_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.PineTree_Autumn_3_2.geometry} material={materials.Orange} />
        <mesh geometry={nodes.PineTree_Autumn_3_3.geometry} material={materials.LightOrange} />
      </group>
    </group>
  );
}
