/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import {
  GenericInstancedSystem,
  type MeshMaterialCombos,
} from "src/canvas/InstancedMeshSystem/GenericInstancingSystem";
import type { Mesh, MeshStandardMaterial, Vector3 } from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plant_5_1: Mesh;
    Plant_5_2: Mesh;
  };
  materials: {
    Yellow: MeshStandardMaterial;
    Pink: MeshStandardMaterial;
  };
};

export function InstancedPlant5({ positions }: { positions: Vector3[] }) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["Plant_5_1", "Yellow"],
    ["Plant_5_2", "Pink"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/Plant_5.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/Plant_5.glb",
  ) as unknown as unknown as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Plant_5_1.geometry} material={materials.Yellow} />
        <mesh geometry={nodes.Plant_5_2.geometry} material={materials.Pink} />
      </group>
    </group>
  );
}
