/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  GenericInstancedSystem,
  MeshMaterialCombos,
} from "src/canvas/InstancedMeshSystem/GenericInstancingSystem";
import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial, Vector3 } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Willow_Snow_2_1: Mesh;
    Willow_Snow_2_2: Mesh;
    Willow_Snow_2_3: Mesh;
  };
  materials: {
    Wood: MeshStandardMaterial;
    Snow: MeshStandardMaterial;
    DarkGreen: MeshStandardMaterial;
  };
};

export function InstancedWillowSnow2({ positions }: { positions: Vector3[] }) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["Willow_Snow_2_1", "Wood"],
    ["Willow_Snow_2_2", "Snow"],
    ["Willow_Snow_2_3", "DarkGreen"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/Willow_Snow_2.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/Willow_Snow_2.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Willow_Snow_2_1.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Willow_Snow_2_2.geometry}
          material={materials.Snow}
        />
        <mesh
          geometry={nodes.Willow_Snow_2_3.geometry}
          material={materials.DarkGreen}
        />
      </group>
    </group>
  );
}
