/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import {
  GenericInstancedSystem,
  type MeshMaterialCombos,
} from "src/canvas/InstancedMeshSystem/GenericInstancingSystem";
import type { Mesh, MeshStandardMaterial, Vector3 } from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    WoodLog_Moss_1: Mesh;
    WoodLog_Moss_2: Mesh;
    WoodLog_Moss_3: Mesh;
    WoodLog_Moss_4: Mesh;
    WoodLog_Moss_5: Mesh;
  };
  materials: {
    Wood: MeshStandardMaterial;
    Green: MeshStandardMaterial;
    Mushroom_Top: MeshStandardMaterial;
    Mushroom_Bottom: MeshStandardMaterial;
    DarkGreen: MeshStandardMaterial;
  };
};

export function InstancedWoodLogMoss({ positions }: { positions: Vector3[] }) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["WoodLog_Moss_1", "Wood"],
    ["WoodLog_Moss_2", "Green"],
    ["WoodLog_Moss_3", "Mushroom_Top"],
    ["WoodLog_Moss_4", "Mushroom_Bottom"],
    ["WoodLog_Moss_5", "DarkGreen"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/WoodLog_Moss.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/WoodLog_Moss.glb",
  ) as unknown as unknown as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.WoodLog_Moss_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.WoodLog_Moss_2.geometry} material={materials.Green} />
        <mesh geometry={nodes.WoodLog_Moss_3.geometry} material={materials.Mushroom_Top} />
        <mesh geometry={nodes.WoodLog_Moss_4.geometry} material={materials.Mushroom_Bottom} />
        <mesh geometry={nodes.WoodLog_Moss_5.geometry} material={materials.DarkGreen} />
      </group>
    </group>
  );
}
