import Layout from "@components/Layout";
import { InfiniteScrollGallery } from "@components/Galleries";
import { ToTopButton } from "@components/ToTopButton";
import { ImageProps } from "src/@types";
import { SeoInfo } from "src/lib/getSeoInfo";

export default function MidjourneyGallery({
  images,
  seo,
}: {
  images: ImageProps[];
  seo: SeoInfo | null;
}) {
  return (
    <Layout
      title={seo?.metaTitle || "Midjourney Images"}
      description={seo?.metaDescription || "A page with all my AI generated art."}
      url={`/midjourney`}
      fullScreen={true}
      image={seo?.ogImage || "/assets/blog/midjourney.png"}
      imageAlt={seo?.ogImageAlt || "a gallery exhibition of art and books generated by AI"}
      keywords={seo?.keywords || ["midjourney", "AI art", "gallery", "AI generated art"]}
    >
      <div className="mb-20 px-3">
        <h1>Midjourney Images</h1>
        <InfiniteScrollGallery images={images} />

        <ToTopButton />
      </div>
    </Layout>
  );
}

export async function getStaticProps() {
  const { getSeoInfo } = await import("src/lib/getSeoInfo");
  const { getDataFromMetadata } = require("../lib/aws");
  const prefix = "assets/midjourney-gallery/";
  const images = getDataFromMetadata(prefix);

  return { props: { images, seo: getSeoInfo("/midjourney") } };
}
