import { BreadCrumbs } from "@components/BreadCrumbs";
import { InfiniteScrollGallery } from "@components/Galleries";
import Layout from "@components/Layout";
import Header from "@components/PostHeader";
import { ToTopButton } from "@components/ToTopButton";
import type { ImageProps } from "src/@types";
import type { SeoInfo } from "src/lib/getSeoInfo";
import { getDataFromMetadata } from "src/lib/imageMetadata";

export default function MidjourneyGallery({
  images,
  seo,
}: {
  images: ImageProps[];
  seo: SeoInfo | null;
}) {
  return (
    <Layout
      title={seo?.metaTitle || "Midjourney Images"}
      description={seo?.metaDescription || "A page with all my AI generated art."}
      url={`/midjourney`}
      fullScreen={true}
      image={seo?.ogImage || "/assets/blog/midjourney.png"}
      imageAlt={seo?.ogImageAlt || "a gallery exhibition of art and books generated by AI"}
      keywords={seo?.keywords || ["midjourney", "AI art", "gallery", "AI generated art"]}
    >
      <div className="pt-5 pb-20 px-3">
        <BreadCrumbs path="midjourney" />
        <Header title="Midjourney Images" subtitle="AI generated art I made with Midjourney" />
        <InfiniteScrollGallery images={images} />

        <ToTopButton />
      </div>
    </Layout>
  );
}

export async function getStaticProps() {
  const { getSeoInfo } = await import("src/lib/getSeoInfo");
  const prefix = "assets/midjourney-gallery/";
  const images = getDataFromMetadata(prefix);

  return { props: { images, seo: getSeoInfo("/midjourney") } };
}
