/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAnimations } from "@react-three/drei";
import { GenericAnimationController } from "src/canvas/Controllers/GenericAnimationController";
import { GLTF } from "three-stdlib";
import {
  AnimationClip,
  Bone,
  Group,
  Mesh,
  MeshStandardMaterial,
  SkinnedMesh,
} from "three";

type GLTFResult = GLTF & {
  nodes: {
    Alpaca_1: SkinnedMesh;
    Alpaca_2: SkinnedMesh;
    Alpaca_3: SkinnedMesh;
    Alpaca_4: SkinnedMesh;
    Alpaca_5: SkinnedMesh;
    Alpaca_6: SkinnedMesh;
    Alpaca_7: SkinnedMesh;
    Body: Bone;
    IKBackLegL: Bone;
    IKFrontLegL: Bone;
    IKBackLegR: Bone;
    IKFrontLegR: Bone;
  };
  materials: {
    Main_Light: MeshStandardMaterial;
    Main: MeshStandardMaterial;
    Main_Dark: MeshStandardMaterial;
    Muzzle: MeshStandardMaterial;
    Hooves: MeshStandardMaterial;
    Eyes_Black: MeshStandardMaterial;
    Eyes_White: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "AnimalArmature|Attack_Headbutt"
  | "AnimalArmature|Attack_Kick"
  | "AnimalArmature|Death"
  | "AnimalArmature|Eating"
  | "AnimalArmature|Gallop"
  | "AnimalArmature|Gallop_Jump"
  | "AnimalArmature|Idle"
  | "AnimalArmature|Idle_2"
  | "AnimalArmature|Idle_Headlow"
  | "AnimalArmature|Idle_HitReact_Left"
  | "AnimalArmature|Idle_HitReact_Right"
  | "AnimalArmature|Jump_toIdle"
  | "AnimalArmature|Walk";

interface GLTFAction extends AnimationClip {
  name: ActionName;
}

type Props = JSX.IntrinsicElements["group"] & {
  animationAction?: ActionName;
};

export default function Model(props: Props) {
  const group = useRef<Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/3d-assets/glb/animals_pack/Alpaca.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <GenericAnimationController
        actions={actions}
        animation={props.animationAction}
      />
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="AnimalArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group name="Alpaca" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Alpaca_1"
              geometry={nodes.Alpaca_1.geometry}
              material={materials.Main_Light}
              skeleton={nodes.Alpaca_1.skeleton}
            />
            <skinnedMesh
              name="Alpaca_2"
              geometry={nodes.Alpaca_2.geometry}
              material={materials.Main}
              skeleton={nodes.Alpaca_2.skeleton}
            />
            <skinnedMesh
              name="Alpaca_3"
              geometry={nodes.Alpaca_3.geometry}
              material={materials.Main_Dark}
              skeleton={nodes.Alpaca_3.skeleton}
            />
            <skinnedMesh
              name="Alpaca_4"
              geometry={nodes.Alpaca_4.geometry}
              material={materials.Muzzle}
              skeleton={nodes.Alpaca_4.skeleton}
            />
            <skinnedMesh
              name="Alpaca_5"
              geometry={nodes.Alpaca_5.geometry}
              material={materials.Hooves}
              skeleton={nodes.Alpaca_5.skeleton}
            />
            <skinnedMesh
              name="Alpaca_6"
              geometry={nodes.Alpaca_6.geometry}
              material={materials.Eyes_Black}
              skeleton={nodes.Alpaca_6.skeleton}
            />
            <skinnedMesh
              name="Alpaca_7"
              geometry={nodes.Alpaca_7.geometry}
              material={materials.Eyes_White}
              skeleton={nodes.Alpaca_7.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/animals_pack/Alpaca.glb");
