/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useRef } from "react";
import { GenericAnimationController } from "src/canvas/Controllers/GenericAnimationController";
import {
  AnimationClip,
  Bone,
  Group,
  MeshStandardMaterial,
  SkinnedMesh,
} from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cow_1: SkinnedMesh;
    Cow_2: SkinnedMesh;
    Cow_3: SkinnedMesh;
    Cow_4: SkinnedMesh;
    Cow_5: SkinnedMesh;
    Cow_6: SkinnedMesh;
    Cow_7: SkinnedMesh;
    Body: Bone;
    IKBackLegL: Bone;
    IKFrontLegL: Bone;
    IKBackLegR: Bone;
    IKFrontLegR: Bone;
  };
  materials: {
    Main: MeshStandardMaterial;
    Muzzle: MeshStandardMaterial;
    Hooves: MeshStandardMaterial;
    Main_Light: MeshStandardMaterial;
    Eye_Black: MeshStandardMaterial;
    Eye_White: MeshStandardMaterial;
    Horns: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "AnimalArmature|Attack_Headbutt"
  | "AnimalArmature|Attack_Kick"
  | "AnimalArmature|Death"
  | "AnimalArmature|Eating"
  | "AnimalArmature|Gallop"
  | "AnimalArmature|Gallop_Jump"
  | "AnimalArmature|Idle"
  | "AnimalArmature|Idle_2"
  | "AnimalArmature|Idle_Headlow"
  | "AnimalArmature|Idle_HitReact_Left"
  | "AnimalArmature|Jump_toIdle"
  | "AnimalArmature|Walk";

interface GLTFAction extends AnimationClip {
  name: ActionName;
}

type Props = JSX.IntrinsicElements["group"] & {
  animationAction?: ActionName;
};

export default function Model(props: Props) {
  const group = useRef<Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/3d-assets/glb/animals_pack/Bull.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <GenericAnimationController
        actions={actions}
        animation={props.animationAction}
      />
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="AnimalArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group name="Cow" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Cow_1"
              geometry={nodes.Cow_1.geometry}
              material={materials.Main}
              skeleton={nodes.Cow_1.skeleton}
            />
            <skinnedMesh
              name="Cow_2"
              geometry={nodes.Cow_2.geometry}
              material={materials.Muzzle}
              skeleton={nodes.Cow_2.skeleton}
            />
            <skinnedMesh
              name="Cow_3"
              geometry={nodes.Cow_3.geometry}
              material={materials.Hooves}
              skeleton={nodes.Cow_3.skeleton}
            />
            <skinnedMesh
              name="Cow_4"
              geometry={nodes.Cow_4.geometry}
              material={materials.Main_Light}
              skeleton={nodes.Cow_4.skeleton}
            />
            <skinnedMesh
              name="Cow_5"
              geometry={nodes.Cow_5.geometry}
              material={materials.Eye_Black}
              skeleton={nodes.Cow_5.skeleton}
            />
            <skinnedMesh
              name="Cow_6"
              geometry={nodes.Cow_6.geometry}
              material={materials.Eye_White}
              skeleton={nodes.Cow_6.skeleton}
            />
            <skinnedMesh
              name="Cow_7"
              geometry={nodes.Cow_7.geometry}
              material={materials.Horns}
              skeleton={nodes.Cow_7.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/animals_pack/Bull.glb");
