/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useRef } from "react";
import { GenericAnimationController } from "src/canvas/Controllers/GenericAnimationController";
import {
  AnimationClip,
  Bone,
  Group,
  MeshStandardMaterial,
  SkinnedMesh,
} from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Donkey_1: SkinnedMesh;
    Donkey_2: SkinnedMesh;
    Donkey_3: SkinnedMesh;
    Donkey_4: SkinnedMesh;
    Donkey_5: SkinnedMesh;
    Donkey_6: SkinnedMesh;
    Donkey_7: SkinnedMesh;
    Donkey_8: SkinnedMesh;
    Body: Bone;
    IKBackLegL: Bone;
    IKFrontLegL: Bone;
    IKBackLegR: Bone;
    IKFrontLegR: Bone;
  };
  materials: {
    Main_Light: MeshStandardMaterial;
    Main: MeshStandardMaterial;
    Hair: MeshStandardMaterial;
    Muzzle: MeshStandardMaterial;
    Hooves: MeshStandardMaterial;
    Main_Dark: MeshStandardMaterial;
    Eye_Dark: MeshStandardMaterial;
    Eye_White: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "AnimalArmature|Attack_Headbutt"
  | "AnimalArmature|Attack_Kick"
  | "AnimalArmature|Death"
  | "AnimalArmature|Eating"
  | "AnimalArmature|Gallop"
  | "AnimalArmature|Gallop_Jump"
  | "AnimalArmature|Idle"
  | "AnimalArmature|Idle_2"
  | "AnimalArmature|Idle_Headlow"
  | "AnimalArmature|Idle_HitReact_Left"
  | "AnimalArmature|Idle_HitReact_Right"
  | "AnimalArmature|Jump_toIdle"
  | "AnimalArmature|Walk";

interface GLTFAction extends AnimationClip {
  name: ActionName;
}

type Props = JSX.IntrinsicElements["group"] & {
  animationAction?: ActionName;
};

export default function Model(props: Props) {
  const group = useRef<Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/3d-assets/glb/animals_pack/Donkey.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <GenericAnimationController
        actions={actions}
        animation={props.animationAction}
      />
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="AnimalArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group name="Donkey" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Donkey_1"
              geometry={nodes.Donkey_1.geometry}
              material={materials.Main_Light}
              skeleton={nodes.Donkey_1.skeleton}
            />
            <skinnedMesh
              name="Donkey_2"
              geometry={nodes.Donkey_2.geometry}
              material={materials.Main}
              skeleton={nodes.Donkey_2.skeleton}
            />
            <skinnedMesh
              name="Donkey_3"
              geometry={nodes.Donkey_3.geometry}
              material={materials.Hair}
              skeleton={nodes.Donkey_3.skeleton}
            />
            <skinnedMesh
              name="Donkey_4"
              geometry={nodes.Donkey_4.geometry}
              material={materials.Muzzle}
              skeleton={nodes.Donkey_4.skeleton}
            />
            <skinnedMesh
              name="Donkey_5"
              geometry={nodes.Donkey_5.geometry}
              material={materials.Hooves}
              skeleton={nodes.Donkey_5.skeleton}
            />
            <skinnedMesh
              name="Donkey_6"
              geometry={nodes.Donkey_6.geometry}
              material={materials.Main_Dark}
              skeleton={nodes.Donkey_6.skeleton}
            />
            <skinnedMesh
              name="Donkey_7"
              geometry={nodes.Donkey_7.geometry}
              material={materials.Eye_Dark}
              skeleton={nodes.Donkey_7.skeleton}
            />
            <skinnedMesh
              name="Donkey_8"
              geometry={nodes.Donkey_8.geometry}
              material={materials.Eye_White}
              skeleton={nodes.Donkey_8.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/animals_pack/Donkey.glb");
