/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useRef } from "react";
import { GenericAnimationController } from "src/canvas/Controllers/GenericAnimationController";
import {
  AnimationClip,
  Bone,
  Group,
  Mesh,
  MeshStandardMaterial,
  SkinnedMesh,
} from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Stag_Horns: Mesh;
    Stag_1: SkinnedMesh;
    Stag_2: SkinnedMesh;
    Stag_3: SkinnedMesh;
    Stag_4: SkinnedMesh;
    Stag_5: SkinnedMesh;
    Body: Bone;
    IKBackLegL: Bone;
    IKFrontLegL: Bone;
    IKBackLegR: Bone;
    IKFrontLegR: Bone;
  };
  materials: {
    ["Material.001"]: MeshStandardMaterial;
    ["Material.003"]: MeshStandardMaterial;
    Material: MeshStandardMaterial;
    ["Material.010"]: MeshStandardMaterial;
    ["Material.001"]: MeshStandardMaterial;
    ["Material.011"]: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export type ActionName =
  | "AnimalArmature|Attack_Headbutt"
  | "AnimalArmature|Attack_Kick"
  | "AnimalArmature|Death"
  | "AnimalArmature|Eating"
  | "AnimalArmature|Gallop"
  | "AnimalArmature|Gallop_Jump"
  | "AnimalArmature|Idle"
  | "AnimalArmature|Idle_2"
  | "AnimalArmature|Idle_Headlow"
  | "AnimalArmature|Idle_HitReact_Left"
  | "AnimalArmature|Idle_HitReact_Right"
  | "AnimalArmature|Jump_toIdle"
  | "AnimalArmature|Walk";

interface GLTFAction extends AnimationClip {
  name: ActionName;
}

type Props = JSX.IntrinsicElements["group"] & {
  animationAction?: ActionName;
};

export default function Model(props: Props) {
  const group = useRef<Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/3d-assets/glb/animals_pack/Stag.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <GenericAnimationController
        actions={actions}
        animation={props.animationAction}
      />
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="AnimalArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group name="Stag" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Stag_1"
              geometry={nodes.Stag_1.geometry}
              material={materials["Material.003"]}
              skeleton={nodes.Stag_1.skeleton}
            />
            <skinnedMesh
              name="Stag_2"
              geometry={nodes.Stag_2.geometry}
              material={materials.Material}
              skeleton={nodes.Stag_2.skeleton}
            />
            <skinnedMesh
              name="Stag_3"
              geometry={nodes.Stag_3.geometry}
              material={materials["Material.010"]}
              skeleton={nodes.Stag_3.skeleton}
            />
            <skinnedMesh
              name="Stag_4"
              geometry={nodes.Stag_4.geometry}
              material={materials["Material.001"]}
              skeleton={nodes.Stag_4.skeleton}
            />
            <skinnedMesh
              name="Stag_5"
              geometry={nodes.Stag_5.geometry}
              material={materials["Material.011"]}
              skeleton={nodes.Stag_5.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/animals_pack/Stag.glb");
