/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useRef } from "react";
import { GenericAnimationController } from "src/canvas/Controllers/GenericAnimationController";
import {
  AnimationClip,
  Bone,
  Group,
  MeshStandardMaterial,
  SkinnedMesh,
} from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Wolf_1: SkinnedMesh;
    Wolf_2: SkinnedMesh;
    Wolf_3: SkinnedMesh;
    Wolf_4: SkinnedMesh;
    Body: Bone;
    IKBackLegL: Bone;
    IKFrontLegL: Bone;
    IKBackLegR: Bone;
    IKFrontLegR: Bone;
  };
  materials: {
    Main: MeshStandardMaterial;
    Main_Light: MeshStandardMaterial;
    Eyes_Black: MeshStandardMaterial;
    Nose: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "AnimalArmature|Attack"
  | "AnimalArmature|Death"
  | "AnimalArmature|Eating"
  | "AnimalArmature|Gallop"
  | "AnimalArmature|Gallop_Jump"
  | "AnimalArmature|Idle"
  | "AnimalArmature|Idle_2"
  | "AnimalArmature|Idle_2_HeadLow"
  | "AnimalArmature|Idle_HitReact_Left"
  | "AnimalArmature|Idle_HitReact_Right"
  | "AnimalArmature|Jump_ToIdle"
  | "AnimalArmature|Walk";

interface GLTFAction extends AnimationClip {
  name: ActionName;
}

type Props = JSX.IntrinsicElements["group"] & {
  animationAction?: ActionName;
};

export default function Model(props: Props) {
  const group = useRef<Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/3d-assets/glb/animals_pack/Wolf.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <GenericAnimationController
        actions={actions}
        animation={props.animationAction}
      />
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="AnimalArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group name="Wolf" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Wolf_1"
              geometry={nodes.Wolf_1.geometry}
              material={materials.Main}
              skeleton={nodes.Wolf_1.skeleton}
            />
            <skinnedMesh
              name="Wolf_2"
              geometry={nodes.Wolf_2.geometry}
              material={materials.Main_Light}
              skeleton={nodes.Wolf_2.skeleton}
            />
            <skinnedMesh
              name="Wolf_3"
              geometry={nodes.Wolf_3.geometry}
              material={materials.Eyes_Black}
              skeleton={nodes.Wolf_3.skeleton}
            />
            <skinnedMesh
              name="Wolf_4"
              geometry={nodes.Wolf_4.geometry}
              material={materials.Nose}
              skeleton={nodes.Wolf_4.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/animals_pack/Wolf.glb");
