/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  GenericInstancedSystem,
  MeshMaterialCombos,
} from "src/canvas/InstancedMeshSystem/GenericInstancingSystem";
import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial, Vector3 } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    BirchTree_2_1: Mesh;
    BirchTree_2_2: Mesh;
    BirchTree_2_3: Mesh;
    BirchTree_2_4: Mesh;
  };
  materials: {
    ["White.001"]: MeshStandardMaterial;
    ["Black.001"]: MeshStandardMaterial;
    ["DarkGreen.001"]: MeshStandardMaterial;
    ["Green.001"]: MeshStandardMaterial;
  };
};

export function InstancedBirchTree2({ positions }: { positions: Vector3[] }) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["BirchTree_2_1", "White.001"],
    ["BirchTree_2_2", "Black.001"],
    ["BirchTree_2_3", "DarkGreen.001"],
    ["BirchTree_2_4", "Green.001"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/BirchTree_2.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/BirchTree_2.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.BirchTree_2_1.geometry}
          material={materials["White.001"]}
        />
        <mesh
          geometry={nodes.BirchTree_2_2.geometry}
          material={materials["Black.001"]}
        />
        <mesh
          geometry={nodes.BirchTree_2_3.geometry}
          material={materials["DarkGreen.001"]}
        />
        <mesh
          geometry={nodes.BirchTree_2_4.geometry}
          material={materials["Green.001"]}
        />
      </group>
    </group>
  );
}
