/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  GenericInstancedSystem,
  MeshMaterialCombos,
} from "src/canvas/InstancedMeshSystem/GenericInstancingSystem";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial, Vector3 } from "three";

type GLTFResult = GLTF & {
  nodes: {
    PineTree_Snow_1_1: Mesh;
    PineTree_Snow_1_2: Mesh;
    PineTree_Snow_1_3: Mesh;
  };
  materials: {
    Wood: MeshStandardMaterial;
    Green: MeshStandardMaterial;
    Snow: MeshStandardMaterial;
  };
};

export function InstancedPineTreeSnow1({
  positions,
}: {
  positions: Vector3[];
}) {
  const meshMaterialCombos: MeshMaterialCombos = [
    ["PineTree_Snow_1_1", "Wood"],
    ["PineTree_Snow_1_2", "Green"],
    ["PineTree_Snow_1_3", "Snow"],
  ];

  return (
    <GenericInstancedSystem
      positions={positions}
      meshMaterialCombos={meshMaterialCombos}
      modelPath={"/3d-assets/glb/nature_pack/PineTree_Snow_1-transformed.glb"}
    />
  );
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/PineTree_Snow_1-transformed.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.PineTree_Snow_1_1.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.PineTree_Snow_1_2.geometry}
          material={materials.Green}
        />
        <mesh
          geometry={nodes.PineTree_Snow_1_3.geometry}
          material={materials.Snow}
        />
      </group>
    </group>
  );
}
