/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type { Mesh, MeshStandardMaterial } from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    sphere_gltf: Mesh;
  };
  materials: {
    aerial_beach_01: MeshStandardMaterial;
  };
};

export function useBeachMaterial() {
  return useGLTF(
    "/3d-assets/glb/aerial_beach_01_1k.glb",
  ) as unknown as unknown as unknown as GLTFResult;
}

useGLTF.preload("/3d-assets/glb/aerial_beach_01_1k.glb");
