/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useRef } from "react";
import { GenericAnimationController } from "src/canvas/Controllers/GenericAnimationController";
import {
  AnimationClip,
  Bone,
  Group,
  MeshStandardMaterial,
  SkinnedMesh,
} from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_1: SkinnedMesh;
    Cylinder_2: SkinnedMesh;
    root: Bone;
  };
  materials: {
    Material: MeshStandardMaterial;
    Brown: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "Armature|Apatosaurus_Attack"
  | "Armature|Apatosaurus_Idle"
  | "Armature|Apatosaurus_Jump"
  | "Armature|Apatosaurus_Run"
  | "Armature|Apatosaurus_Walk"
  | "Armature|Stegosaurus_Death";

interface GLTFAction extends AnimationClip {
  name: ActionName;
}

type Props = JSX.IntrinsicElements["group"] & {
  animationAction?: ActionName;
};

export default function Model(props: Props) {
  const group = useRef<Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/3d-assets/glb/dinosaurs_pack/Apatosaurus.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <GenericAnimationController
        actions={actions}
        animation={props.animationAction}
      />
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={300}>
            <primitive object={nodes.root} />
          </group>
          <group
            name="Cylinder"
            position={[0, 1.86, 1.07]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Cylinder_1"
              geometry={nodes.Cylinder_1.geometry}
              material={materials.Material}
              skeleton={nodes.Cylinder_1.skeleton}
            />
            <skinnedMesh
              name="Cylinder_2"
              geometry={nodes.Cylinder_2.geometry}
              material={materials.Brown}
              skeleton={nodes.Cylinder_2.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/dinosaurs_pack/Apatosaurus.glb");
