/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useRef } from "react";
import { GenericAnimationController } from "src/canvas/Controllers/GenericAnimationController";
import {
  AnimationClip,
  Bone,
  Group,
  MeshStandardMaterial,
  SkinnedMesh,
} from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Parasaurolophus_1: SkinnedMesh;
    Parasaurolophus_2: SkinnedMesh;
    Parasaurolophus_3: SkinnedMesh;
    Parasaurolophus_4: SkinnedMesh;
    root: Bone;
  };
  materials: {
    LightYellow: MeshStandardMaterial;
    Green: MeshStandardMaterial;
    LightGreen: MeshStandardMaterial;
    Red: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "Armature|Parasaurolophus_Attack"
  | "Armature|Parasaurolophus_Death"
  | "Armature|Parasaurolophus_Idle"
  | "Armature|Parasaurolophus_Jump"
  | "Armature|Parasaurolophus_Run"
  | "Armature|Parasaurolophus_Walk";

interface GLTFAction extends AnimationClip {
  name: ActionName;
}

type Props = JSX.IntrinsicElements["group"] & {
  animationAction?: ActionName;
};

export default function Model(props: Props) {
  const group = useRef<Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/3d-assets/glb/dinosaurs_pack/Parasaurolophus.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <GenericAnimationController
        actions={actions}
        animation={props.animationAction}
      />
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.root} />
          </group>
          <group
            name="Parasaurolophus"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Parasaurolophus_1"
              geometry={nodes.Parasaurolophus_1.geometry}
              material={materials.LightYellow}
              skeleton={nodes.Parasaurolophus_1.skeleton}
            />
            <skinnedMesh
              name="Parasaurolophus_2"
              geometry={nodes.Parasaurolophus_2.geometry}
              material={materials.Green}
              skeleton={nodes.Parasaurolophus_2.skeleton}
            />
            <skinnedMesh
              name="Parasaurolophus_3"
              geometry={nodes.Parasaurolophus_3.geometry}
              material={materials.LightGreen}
              skeleton={nodes.Parasaurolophus_3.skeleton}
            />
            <skinnedMesh
              name="Parasaurolophus_4"
              geometry={nodes.Parasaurolophus_4.geometry}
              material={materials.Red}
              skeleton={nodes.Parasaurolophus_4.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/dinosaurs_pack/Parasaurolophus.glb");
